import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url)
    const zohoId = searchParams.get('zohoId')

    if (!zohoId) {
      return NextResponse.json({ success: false, error: 'Missing zohoId' }, { status: 400 })
    }

    // Resolve parent accountId
    let accountId: string | null = null

    // 1. Check if the zohoId is an Account directly
    const account = await prisma.account.findFirst({
      where: {
        OR: [
          { id: zohoId },
          { zohoId: zohoId }
        ]
      }
    })

    if (account) {
      accountId = account.id
    } else {
      // 2. Try matching as Deal
      const deal = await prisma.deal.findFirst({
        where: {
          OR: [
            { id: zohoId },
            { zohoId: zohoId }
          ]
        }
      })
      if (deal) {
        accountId = deal.accountId
      } else {
        // 3. Try matching as Invoice
        const invoice = await prisma.invoice.findFirst({
          where: {
            OR: [
              { id: zohoId },
              { zohoId: zohoId }
            ]
          }
        })
        if (invoice) {
          accountId = invoice.accountId
        } else {
          // 4. Try matching as SalesOrder
          const so = await prisma.salesOrder.findFirst({
            where: {
              OR: [
                { id: zohoId },
                { zohoId: zohoId }
              ]
            }
          })
          if (so) {
            accountId = so.accountId
          } else {
            // 5. Try matching as Quote
            const quote = await prisma.quote.findFirst({
              where: {
                OR: [
                  { id: zohoId },
                  { zohoId: zohoId }
                ]
              }
            })
            if (quote) {
              accountId = quote.accountId
            }
          }
        }
      }
    }

    let calls: any[] = []
    let sms: any[] = []
    let notes: any[] = []

    if (accountId) {
      // Fetch CallLogs, SmsMessages, Notes linked to the account
      calls = await prisma.callLog.findMany({
        where: { accountId },
        include: { author: { select: { name: true } } },
        orderBy: { createdAt: 'desc' }
      })

      sms = await prisma.smsMessage.findMany({
        where: { accountId },
        include: { author: { select: { name: true } } },
        orderBy: { createdAt: 'desc' }
      })

      notes = await prisma.note.findMany({
        where: { accountId },
        include: { author: { select: { name: true } } },
        orderBy: { createdAt: 'desc' }
      })
    } else {
      // Fallback: search by direct zohoId matches if we couldn't resolve the parent account
      calls = await prisma.callLog.findMany({
        where: { salesOrderId: zohoId },
        include: { author: { select: { name: true } } },
        orderBy: { createdAt: 'desc' }
      })
    }

    // Format Calls
    const formattedCalls = calls.map(c => ({
      id: c.id,
      type: 'CALL' as const,
      createdAt: c.createdAt,
      direction: c.direction,
      duration: c.duration,
      status: c.status,
      fromNumber: c.fromNumber,
      toNumber: c.toNumber,
      notes: c.notes,
      recordingUrl: c.recordingUrl,
      authorName: c.authorId === 'system' ? 'System Sync' : (c.author?.name || 'System Sync')
    }))

    // Format SMS Messages
    const formattedSms = sms.map(s => ({
      id: s.id,
      type: 'SMS' as const,
      createdAt: s.createdAt,
      direction: s.direction,
      body: s.body,
      fromNumber: s.fromNumber,
      toNumber: s.toNumber,
      mediaUrl: s.mediaUrl,
      authorName: s.direction === 'OUTBOUND' ? (s.author?.name || 'Agent') : 'Customer'
    }))

    // Format Notes
    const formattedNotes = notes.map(n => ({
      id: n.id,
      type: 'NOTE' as const,
      createdAt: n.createdAt,
      body: n.content,
      authorName: n.author?.name || 'Agent',
      isAutoGenerated: n.isAutoGenerated
    }))

    // Merge and sort all chronologically in descending order
    const communications = [
      ...formattedCalls,
      ...formattedSms,
      ...formattedNotes
    ].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())

    return NextResponse.json({ success: true, communications })
  } catch (error: any) {
    console.error('Failed to fetch communications:', error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}
