import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { prisma } from '../../netlify/functions/lib/prisma'
import { applyInvoicePersistencePlan, __testOnlyApplyInvoicePersistencePlan, buildPaymentPersistencePlan, type InvoicePersistencePlan } from './sync-engine'

const marker = `TEST-PLAN-${Date.now()}`; let accountId = ''; let userId = ''
const plan = (mode: InvoicePersistencePlan['mode'], zohoId: string): InvoicePersistencePlan => ({ mode, identity: { zohoId }, createData: { zohoId, account: { connect: { id: accountId } }, amount: 100, status: 'Sent', issueDate: new Date(), items: {} }, updateData: { amount: 125, status: 'Paid', paymentMade: 50 }, lineItems: [{ line_item_id: '1', name: 'Test', quantity: 1, rate: 100, item_total: 100 }], payments: buildPaymentPersistencePlan([{ payment_id: `${zohoId}-p1`, invoice_id: zohoId, amount: 50, date: '2026-01-01' }], ''), reviewUpserts: [{ documentType: 'INVOICE', documentRef: zohoId, reasonCode: 'TEST_REVIEW' }], reviewResolutions: [] })

describe('applyInvoicePersistencePlan (disposable PostgreSQL)', () => {
  beforeAll(async () => { const user = await prisma.user.create({ data: { email: `${marker}@example.test`, name: 'Test', role: 'ADMIN' } }); userId = user.id; const account = await prisma.account.create({ data: { zohoId: marker, name: 'Test Account', ownerId: userId } }); accountId = account.id })
  afterAll(async () => { const invoices = await prisma.invoice.findMany({ where: { zohoId: { startsWith: marker } }, select: { id: true } }); const ids = invoices.map((x) => x.id); await prisma.financialReview.deleteMany({ where: { documentRef: { startsWith: marker } } }); await prisma.lineItem.deleteMany({ where: { invoiceId: { in: ids } } }); await prisma.payment.deleteMany({ where: { invoiceDbId: { in: ids } } }); await prisma.invoice.deleteMany({ where: { id: { in: ids } } }); await prisma.account.delete({ where: { id: accountId } }); await prisma.user.delete({ where: { id: userId } }) })
  it('creates and replays without duplicates', async () => { const id = `${marker}-CREATE`; const p = plan('create-or-update', id); const first = await applyInvoicePersistencePlan(p); await applyInvoicePersistencePlan(p); const payment = await prisma.payment.findUnique({ where: { zohoId: `${id}-p1` }, include: { invoice: true } }); expect((await prisma.invoice.count({ where: { zohoId: id } }))).toBe(1); expect(payment?.invoiceId).toBe(id); expect(payment?.invoiceDbId).toBe(first.id); expect(payment?.invoice?.id).toBe(first.id); expect(await prisma.payment.count({ where: { invoiceDbId: first.id } })).toBe(1); expect(await prisma.financialReview.count({ where: { documentRef: id } })).toBe(1) })
  it('updates an existing invoice and replaces line items', async () => { const id = `${marker}-UPDATE`; const p = plan('create-or-update', id); const existing = await prisma.invoice.create({ data: p.createData }); p.mode = 'update-existing'; p.identity.id = existing.id; const result = await applyInvoicePersistencePlan(p); expect(result.status).toBe('Paid'); expect(await prisma.lineItem.count({ where: { invoiceId: existing.id } })).toBe(1) })
  it('rolls back all writes on a database failure', async () => { const id = `${marker}-ROLLBACK`; const p = plan('create-or-update', id); p.payments.payments[0] = { ...p.payments.payments[0], create: { ...p.payments.payments[0].create, amount: Number.NaN } }; await expect(applyInvoicePersistencePlan(p)).rejects.toThrow(); expect(await prisma.invoice.findUnique({ where: { zohoId: id } })).toBeNull(); expect(await prisma.financialReview.count({ where: { documentRef: id } })).toBe(0) })
  it.each(['afterInvoice', 'afterPayments', 'afterLineItems', 'afterReviews'] as const)('%s rollback leaves no invoice or review', async (stage) => { const id = `${marker}-${stage}`; const p = plan('create-or-update', id); await expect(__testOnlyApplyInvoicePersistencePlan(p, { [stage]: () => { throw new Error(stage) } })).rejects.toThrow(stage); expect(await prisma.invoice.findUnique({ where: { zohoId: id } })).toBeNull(); expect(await prisma.financialReview.count({ where: { documentRef: id } })).toBe(0) })
  it('resolved review remains resolved on replay', async () => { const id = `${marker}-RESOLVED`; const p = plan('create-or-update', id); await applyInvoicePersistencePlan(p); await prisma.financialReview.updateMany({ where: { documentRef: id }, data: { status: 'RESOLVED' } }); await applyInvoicePersistencePlan(p); expect((await prisma.financialReview.findFirst({ where: { documentRef: id } }))?.status).toBe('RESOLVED') })
  it('concurrent identical review actions remain unique', async () => { const id = `${marker}-CONCURRENT`; const p = plan('create-or-update', id); const results = await Promise.all([applyInvoicePersistencePlan(p), applyInvoicePersistencePlan(p)]); expect(new Set(results.map((x) => x.id)).size).toBe(1); expect(await prisma.invoice.count({ where: { zohoId: id } })).toBe(1); expect(await prisma.payment.count({ where: { zohoId: `${id}-p1` } })).toBe(1); expect(await prisma.financialReview.count({ where: { documentRef: id, reasonCode: 'TEST_REVIEW' } })).toBe(1); expect(await prisma.lineItem.count({ where: { invoiceId: results[0].id } })).toBe(1) })
})
