import { trainingModules } from './trainingData'
import { agentAllowed, type TelegramBinding } from './telegram-policy'

// Reviewed navigation/behavior descriptions, not an unrestricted dump of source,
// environment variables, operational handoffs, or customer records.
export const systemTopics = [
  { title: 'System overview', path: '/dashboard', keywords: 'system portal hub overview features architecture integrations', text: 'The Titan portal brings together sales, accounts, orders, invoices, calls, messages, collections, tasks, catalog, commissions, shipping, training and administration. The application uses Next.js, PostgreSQL/Prisma, and Netlify functions. Zoho integration code connects business records; a local record is not proof of current provider state.', source: 'AGENTS.md' },
  { title: 'Sales and lead calling', path: '/sales/leads-calling', keywords: 'sales leads calling customers accounts pipeline follow up', text: 'Use Sales and the Leads Calling screen for lead/account work. For a specific customer, identify the exact company before reviewing its records. Telegram can retrieve accessible account context and a bounded sample of imported call transcripts; it cannot place calls.', source: 'src/app/sales/leads-calling/page.tsx' },
  { title: 'Orders, invoices and billing', path: '/docs', keywords: 'documents quotes estimates sales orders invoices billing balances', text: 'Sales Docs is the portal area for sales documents. Telegram can review the available invoice and order snapshots for an accessible account, including recorded amount, balance, status and dates. It does not issue invoices, charge cards, refund payments, or certify provider synchronization.', source: 'src/lib/telegram-agent.ts' },
  { title: 'Collections', path: '/collections', keywords: 'collections overdue aging debt payment promise follow up', text: 'Collections handles overdue customer balances and follow-up work. Telegram can retrieve up to 20 overdue invoice snapshots, review account context, draft a follow-up, and propose a portal task. A payment promise is not a verified payment; the bot cannot send the draft to a customer.', source: 'src/lib/telegram-agent.ts' },
  { title: 'Tasks and operations', path: '/tasks', keywords: 'tasks operations due overdue priorities handoffs complete', text: 'Tasks tracks follow-up work. Telegram reads up to 20 overdue or next-seven-day tasks. It can propose a portal-only task assigned to the requester with an exact account and due date, or completion backed by concrete evidence. Approval is required unless an existing eligible task-creation auto policy applies. Creating a task does not perform its underlying work.', source: 'src/lib/telegram-actions.ts' },
  { title: 'Catalog and product selection', path: '/catalog', keywords: 'catalog products sku price stock equipment blade specifications', text: 'The published catalog supplies product names, SKUs, listed prices, applications, sizes, equipment and local stock snapshots. Telegram can compare these listed facts. Unlisted compatibility, safety specifications and real-time stock require further verification.', source: 'src/lib/telegram-agent.ts' },
  { title: 'Messaging', path: '/messages', keywords: 'messages sms texts communications customers inbox', text: 'Messages is the portal customer-communication area. Telegram can review up to 10 recent text records for an accessible account, but it has no customer-send tool. Preparing a draft does not send it.', source: 'src/lib/telegram-agent.ts' },
  { title: 'Shipping', path: '/shipping', keywords: 'shipping labels tracking carriers fulfillment easyship', text: 'Shipping is the portal shipping workspace; Easyship integration exists in the application. Telegram currently has no live shipment, rate, label-purchase or carrier-tracking tool. It can explain the documented workflow and identify the portal screen without claiming shipment status.', source: 'AGENTS.md' },
  { title: 'Commissions and performance', path: '/commissions', keywords: 'commission compensation earnings payout profit performance stats', text: 'Commissions is the portal commission/earnings area and /stats contains performance views. Management can use Telegram to review bounded stored invoice profit calculations and unresolved calculation/sync flags. Telegram does not retrieve payroll, certify a payout, or change compensation.', source: 'AGENTS.md; src/lib/telegram-agent.ts' },
  { title: 'Time tracking and training', path: '/timeclock', keywords: 'timeclock clock attendance payroll training guides learning', text: 'Timeclock is the time-tracking screen. /training contains the official portal training modules, searchable by Telegram. The bot has no attendance-edit or payroll-processing tool. Use the relevant portal workflow and its access controls.', source: 'AGENTS.md; src/lib/trainingData.ts' },
  { title: 'Telegram assistant and roles', path: '/telegram', keywords: 'telegram bot agent system chat help directions accounting data zoho billing graphics operations memory slow reply', text: 'Use /system for broad portal questions, /help for roles, and /directions for the active role. Role selection persists. For the system assistant, up to six successful recent user requests from the same pairing, role and portal permission role can supply follow-up context for 24 hours; previous assistant answers are not reused as facts. Live records are re-read. Administrators can use /monitor daily for an 8 AM Phoenix digest plus threshold alerts; /monitor status and /monitor off control it. Reviews run every 15 minutes and count recorded calls, messages, communication events, processing jobs, and overdue tasks; content samples are bounded. The scheduled dispatcher processes one pending reply per chat per minute, so backlog adds delay. Disconnect on /telegram. ChatGPT history and image attachments are not available.', source: 'src/lib/telegram-service.ts; netlify/functions/telegram-agent-dispatch.ts' },
  { title: 'Flyers and campaign planning', path: '/admin/flyer-studio', keywords: 'flyer graphics design campaign marketing email offers image', text: 'The portal has Flyer Studio and /admin/campaigns. In Telegram, /graphics can draft copy and campaign plans or propose a fixed-template SVG for a verified product. It cannot reproduce arbitrary layouts, generate photographs, schedule campaigns or send them. A previous ChatGPT flyer style needs its instructions and examples supplied separately.', source: 'src/lib/telegram-directions.ts', management: true },
  { title: 'Zoho and data integrations', path: '/admin/data-integrations', keywords: 'zoho crm books inventory integrations sync mapping refresh imports', text: 'The application integrates Zoho CRM and Books. /admin/sync-conflicts is a relevant screen for conflicts. Telegram reads local portal records and available timestamps; it has no direct live Zoho configuration editor or provider-write tool. Diagnose the exact application, record and error. Configuration presence alone does not verify authentication or synchronization.', source: 'AGENTS.md; src/lib/telegram-directions.ts', management: true },
  { title: 'System health and administration', path: '/admin/system-health', keywords: 'health status errors failure configuration debugging admin permissions users maintenance', text: 'Use System Health for administrative investigation and /admin/users for user management. The system assistant can report a limited configuration-presence check and counts of your own Telegram jobs. It does not inspect arbitrary logs, reveal secrets, execute SQL, grant permissions or declare all providers healthy. A concrete error and timestamp help locate a problem.', source: 'src/app/admin/system-health/page.tsx', management: true },
  { title: 'Voice and call evidence', path: '/admin/communications', keywords: 'voice retell twilio call transcript recording reconciliation caller', text: 'Voice integration and reconciliation workflows exist in the portal. Telegram reads only imported transcripts linked to an accessible account, up to eight calls longer than 15 seconds. Imported text may be incomplete; it cannot verify caller identity, play recordings, place calls, or change routing.', source: 'src/lib/telegram-agent.ts', management: true },
]

const ignored = new Set('a an the what where how is are i me my to of for in on can do does about tell please system anything everything you your'.split(' '))
export function searchSystemKnowledge(query: string, role: string) {
  const words = [...new Set(query.toLowerCase().match(/[a-z0-9]+/g) || [])].filter(word => word.length > 2 && !ignored.has(word)).slice(0, 20)
  const management = agentAllowed('accounting', role)
  const candidates = systemTopics.filter(topic => !topic.management || management).map(topic => ({ ...topic, kind: 'system guide', score: words.reduce((n, word) => n + (topic.title.toLowerCase().includes(word) ? 5 : 0) + (topic.keywords.includes(word) ? 3 : 0) + (topic.text.toLowerCase().includes(word) ? 1 : 0), 0) }))
  const training = trainingModules.filter(module => management || !['Admin & Management', 'Timeclock & Payroll', 'Commissions & Performance'].includes(module.category)).map(module => ({ title: module.title, path: '/training', text: module.content.slice(0, 4500), source: `training:${module.id}`, kind: 'training guide', score: words.reduce((n, word) => n + (module.title.toLowerCase().includes(word) ? 4 : 0) + (module.content.toLowerCase().includes(word) ? 1 : 0), 0) }))
  const ranked = [...candidates, ...training].filter(item => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 5)
  const selected = !words.length ? candidates.slice(0, 5) : ranked.length ? ranked : /\b(system|portal|hub|features)\b/i.test(query) ? candidates.slice(0, 1) : []
  return { checkedAgainstSource: '2026-09-26', coverage: 'Reviewed system map and bounded training search, not exhaustive source-code access or live provider health.', matches: selected.map(({ title, path, text, source, kind }) => ({ title, url: `https://www.tdusales.com${path}`, text, source, kind })) }
}

export function recentSystemRequests(rows: Array<{ payload: unknown; result: unknown }>, binding: TelegramBinding, role: string) {
  const requests: string[] = []
  for (const row of rows) {
    const p = row.payload as Partial<TelegramBinding> & { text?: unknown } | null
    const r = row.result as { agent?: string; portalRole?: string } | null
    if (!p || p.nonce !== binding.nonce || p.chatId !== binding.chatId || p.telegramId !== binding.telegramId || r?.agent !== 'system' || r.portalRole !== role || typeof p.text !== 'string') continue
    if (p.text.trim().toLowerCase() === '/reset') break
    if (!p.text.startsWith('/')) requests.push(p.text.slice(0, 1500))
  }
  return requests.reverse()
}
