import { authenticateFunction, withFunctionAuth } from "./lib/auth-middleware"
import { Handler } from "@netlify/functions"
import { corsHeaders, handleOptions } from "./lib/cors"
import { prisma } from "./lib/prisma"

const authenticatedHandler: Handler = async (event) => {
  if (event.httpMethod === "OPTIONS") return handleOptions()

  if (event.httpMethod !== "POST") {
    return {
      statusCode: 405,
      headers: corsHeaders,
      body: JSON.stringify({ success: false, error: "Method Not Allowed" })
    }
  }

  try {
    const caller = await authenticateFunction(event)
    const { accountId, content } = JSON.parse(event.body || "{}")

    if (!accountId || !content) {
      return {
        statusCode: 400,
        headers: corsHeaders,
        body: JSON.stringify({ success: false, error: "Missing accountId or content" })
      }
    }

    const callerId = String(caller.dbId || caller.userId || "")
    const author = callerId ? await prisma.user.findUnique({ where: { id: callerId } }) : null
    if (!author) {
      return {
        statusCode: 400,
        headers: corsHeaders,
        body: JSON.stringify({ success: false, error: "Unauthorized: User not found" })
      }
    }

    const account = await prisma.account.findUnique({ where: { id: accountId }, select: { ownerId: true } })
    const role = String(caller.role || "").toLowerCase()
    const privileged = role.includes("admin") || role.includes("manager")
    if (!account || (!privileged && account.ownerId !== callerId)) {
      return { statusCode: 403, headers: corsHeaders, body: JSON.stringify({ success: false, error: "Forbidden" }) }
    }

    const note = await prisma.note.create({
      data: {
        accountId,
        authorId: author.id,
        content,
        sentiment: "Neutral",
        isAutoGenerated: false
      }
    })

    return {
      statusCode: 200,
      headers: corsHeaders,
      body: JSON.stringify({ success: true, note })
    }
  } catch (err: any) {
    console.error("Add Note Function Error:", err)
    return {
      statusCode: 500,
      headers: corsHeaders,
      body: JSON.stringify({ success: false, error: err.message })
    }
  }
}

export const handler = withFunctionAuth(authenticatedHandler)
