import { withFunctionAuth } from "./lib/auth-middleware"
import { Handler } from "@netlify/functions"

import { prisma } from "./lib/prisma"

const authenticatedHandler: Handler = async (event) => {
  const cors = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
  }

  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: cors, body: "" }

  try {
    if (event.httpMethod === "POST") {
      // Save a call log
      const body = JSON.parse(event.body || "{}")
      const { invoiceId, outcome, notes, callerName, contactReached, spokeTo, promiseDate, followUpDate, durationMinutes, userId } = body

      if (!invoiceId) return { statusCode: 400, headers: cors, body: JSON.stringify({ error: "invoiceId required" }) }

      // Find the invoice to get account info
      const invoice = await prisma.invoice.findFirst({
        where: { OR: [{ id: invoiceId }, { zohoId: invoiceId }] },
        include: { account: { include: { owner: true } } }
      })

      if (!invoice) return { statusCode: 404, headers: cors, body: JSON.stringify({ error: "Invoice not found" }) }

      // Resolve author: try userId first, then fall back to @titandiamond email
      let defaultUser = userId
        ? await prisma.user.findUnique({ where: { id: userId } })
        : null
      if (!defaultUser) {
        defaultUser = await prisma.user.findFirst({ where: { email: { contains: "@titandiamond" } } })
      }
      if (!defaultUser) return { statusCode: 400, headers: cors, body: JSON.stringify({ error: "No user found" }) }

      const outcomeLabels: Record<string, string> = {
        left_voicemail: "Voicemail",
        no_answer: "No Answer",
        promise_to_pay: "Promise to Pay",
        early_pay_discount: "Discount Agreed",
        paid_in_full: "Paid in Full",
        disputed: "Disputed",
        callback_requested: "Callback",
        other: "Other",
      }

      const content = [
        `📞 Collection Call — Invoice ${(invoice.items as any)?.invoiceNumber || invoice.zohoId?.slice(-6)}`,
        `Outcome: ${outcomeLabels[outcome] || outcome}`,
        contactReached ? `Spoke With: ${spokeTo || "Contact"}` : "No contact reached",
        durationMinutes ? `Duration: ${durationMinutes} min` : null,
        promiseDate ? `Promise to Pay by: ${promiseDate}` : null,
        followUpDate ? `Follow-up: ${followUpDate}` : null,
        notes ? `Notes: ${notes}` : null,
        `By: ${callerName || "Staff"}`,
      ].filter(Boolean).join("\n")

      const note = await prisma.note.create({
        data: {
          accountId: invoice.accountId,
          authorId: defaultUser.id,
          content,
          isAutoGenerated: false,
          sentiment: ["paid_in_full", "promise_to_pay"].includes(outcome) ? "positive" :
                     ["disputed"].includes(outcome) ? "negative" : "neutral",
        }
      })

      // Maintain lastCalledAt on the account
      try {
        await prisma.account.update({
          where: { id: invoice.accountId },
          data: { lastCalledAt: new Date() }
        })
      } catch (err) {
        console.warn("Failed to update lastCalledAt on account:", err)
      }

      // Push Note to Zoho CRM
      if (invoice.account?.zohoId) {
        const { pushZohoNote } = await import("./lib/zoho-auth")
        await pushZohoNote(invoice.account.zohoId, `Collection Call Log: ${outcomeLabels[outcome] || outcome}`, content)
      }

      return { statusCode: 200, headers: cors, body: JSON.stringify({ success: true, noteId: note.id }) }
    }

    // GET — fetch call logs for an invoice
    const { invoiceId } = event.queryStringParameters || {}
    if (!invoiceId) return { statusCode: 400, headers: cors, body: JSON.stringify({ error: "invoiceId required" }) }

    const invoice = await prisma.invoice.findFirst({
      where: { OR: [{ id: invoiceId }, { zohoId: invoiceId }] },
    })
    if (!invoice) return { statusCode: 404, headers: cors, body: JSON.stringify({ error: "Not found" }) }

    const notes = await prisma.note.findMany({
      where: { accountId: invoice.accountId, content: { contains: "Collection Call" } },
      include: { author: true },
      orderBy: { createdAt: "desc" },
    })

    return {
      statusCode: 200,
      headers: cors,
      body: JSON.stringify({ success: true, logs: notes })
    }
  } catch (err: any) {
    console.error("log-collection-call error:", err)
    return { statusCode: 500, headers: cors, body: JSON.stringify({ error: err.message }) }
  }
}

export const handler = withFunctionAuth(authenticatedHandler)
