import { authenticateFunction, withFunctionAuth } from "./lib/auth-middleware"
import { Handler } from "@netlify/functions"

import { prisma } from "./lib/prisma"
import { isAdminRole } from "../../src/lib/roles"

const authenticatedHandler: Handler = async (event) => {
  const cors = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
  }

  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: cors, body: "" }

  try {
    const sessionUser = await authenticateFunction(event)
    const actorId = sessionUser.dbId || sessionUser.userId
    if (event.httpMethod === "POST") {
      // Save a call log
      const body = JSON.parse(event.body || "{}")
      const { invoiceId, invoiceIds, outcome, notes, callerName, contactReached, spokeTo, promiseDate, followUpDate, durationMinutes } = body

      const requestedInvoiceIds = Array.from(new Set([
        ...(Array.isArray(invoiceIds) ? invoiceIds : []),
        ...(invoiceId ? [invoiceId] : []),
      ].filter(Boolean))) as string[]
      if (requestedInvoiceIds.length === 0) return { statusCode: 400, headers: cors, body: JSON.stringify({ error: "invoiceId or invoiceIds required" }) }

      const invoices = await prisma.invoice.findMany({
        where: { OR: [{ id: { in: requestedInvoiceIds } }, { zohoId: { in: requestedInvoiceIds } }] },
        include: { account: { include: { owner: true } } }
      })

      if (invoices.length !== requestedInvoiceIds.length) return { statusCode: 404, headers: cors, body: JSON.stringify({ error: "One or more invoices were not found" }) }
      const invoice = invoices[0]
      if (invoices.some(item => item.accountId !== invoice.accountId)) {
        return { statusCode: 400, headers: cors, body: JSON.stringify({ error: "A campaign disposition must contain invoices from one account" }) }
      }

      if (!isAdminRole(sessionUser.role) && invoice.account.ownerId !== actorId) {
        return { statusCode: 403, headers: cors, body: JSON.stringify({ error: "You can only log collection calls for your own accounts" }) }
      }

      const defaultUser = actorId ? await prisma.user.findUnique({ where: { id: actorId } }) : null
      if (!defaultUser) return { statusCode: 403, headers: cors, body: JSON.stringify({ error: "Signed-in user is not linked to a local account" }) }

      const outcomeLabels: Record<string, string> = {
        left_voicemail: "Voicemail",
        no_answer: "No Answer",
        promise_to_pay: "Promise to Pay",
        early_pay_discount: "Discount Agreed",
        paid_in_full: "Paid in Full",
        disputed: "Disputed",
        callback_requested: "Callback",
        other: "Other",
      }

      const content = [
        `📞 Collection Call — Invoice${invoices.length > 1 ? "s" : ""} ${invoices.map(item => (item.items as any)?.invoiceNumber || item.zohoId?.slice(-6)).join(", ")}`,
        `Outcome: ${outcomeLabels[outcome] || outcome}`,
        contactReached ? `Spoke With: ${spokeTo || "Contact"}` : "No contact reached",
        durationMinutes ? `Duration: ${durationMinutes} min` : null,
        promiseDate ? `Promise to Pay by: ${promiseDate}` : null,
        followUpDate ? `Follow-up: ${followUpDate}` : null,
        notes ? `Notes: ${notes}` : null,
        `By: ${defaultUser.name || callerName || "Staff"}`,
      ].filter(Boolean).join("\n")

      const [note] = await prisma.$transaction([
        prisma.note.create({
          data: {
            accountId: invoice.accountId,
            authorId: defaultUser.id,
            content,
            isAutoGenerated: false,
            sentiment: ["paid_in_full", "promise_to_pay"].includes(outcome) ? "positive" :
                       ["disputed"].includes(outcome) ? "negative" : "neutral",
          }
        }),
        prisma.account.update({
          where: { id: invoice.accountId },
          data: { lastCalledAt: new Date() }
        }),
      ])

      // Push Note to Zoho CRM
      let zohoSynced = false
      if (invoice.account?.zohoId) {
        try {
          const { pushZohoNote } = await import("./lib/zoho-auth")
          await pushZohoNote(invoice.account.zohoId, `Collection Call Log: ${outcomeLabels[outcome] || outcome}`, content)
          zohoSynced = true
        } catch (zohoError) {
          console.error("Collection call saved locally but Zoho note sync failed:", zohoError)
        }
      }

      return { statusCode: 200, headers: cors, body: JSON.stringify({ success: true, noteId: note.id, invoiceCount: invoices.length, zohoSynced }) }
    }

    // GET — fetch call logs for an invoice
    const { invoiceId } = event.queryStringParameters || {}
    if (!invoiceId) return { statusCode: 400, headers: cors, body: JSON.stringify({ error: "invoiceId required" }) }

    const invoice = await prisma.invoice.findFirst({
      where: { OR: [{ id: invoiceId }, { zohoId: invoiceId }] },
      include: { account: { select: { ownerId: true } } },
    })
    if (!invoice) return { statusCode: 404, headers: cors, body: JSON.stringify({ error: "Not found" }) }
    if (!isAdminRole(sessionUser.role) && invoice.account.ownerId !== actorId) {
      return { statusCode: 403, headers: cors, body: JSON.stringify({ error: "You can only view collection calls for your own accounts" }) }
    }

    const notes = await prisma.note.findMany({
      where: { accountId: invoice.accountId, content: { contains: "Collection Call" } },
      include: { author: true },
      orderBy: { createdAt: "desc" },
    })

    return {
      statusCode: 200,
      headers: cors,
      body: JSON.stringify({ success: true, logs: notes })
    }
  } catch (err: any) {
    console.error("log-collection-call error:", err)
    return { statusCode: 500, headers: cors, body: JSON.stringify({ error: err.message }) }
  }
}

export const handler = withFunctionAuth(authenticatedHandler)
