import { Handler } from "@netlify/functions"
import { PrismaClient } from "@prisma/client"
import { getZohoAccessToken } from "./lib/zoho-auth"

const ZOHO_DC = process.env.ZOHO_DC || 'com'

const prisma = new PrismaClient()

const VALID_TIMEZONES = ["EST", "CST", "MST", "PST", "AST", "HST", ""]

export const handler: Handler = async (event) => {
  const cors = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, PATCH, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  }

  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: cors, body: "" }

  try {
    if (event.httpMethod === "PATCH" || event.httpMethod === "POST") {
      const body = JSON.parse(event.body || "{}")
      const { accountId, zohoId, timeZone, note } = body

      if (timeZone && !VALID_TIMEZONES.includes(timeZone)) {
        return {
          statusCode: 400,
          headers: cors,
          body: JSON.stringify({ success: false, error: `Invalid timezone. Must be one of: ${VALID_TIMEZONES.filter(Boolean).join(", ")}` })
        }
      }

      // Find account by zohoId or internal id
      let account = null
      if (zohoId) {
        account = await prisma.account.findUnique({ where: { zohoId } })
      }
      if (!account && accountId) {
        account = await prisma.account.findUnique({ where: { id: accountId } })
      }

      if (!account) {
        return { statusCode: 404, headers: cors, body: JSON.stringify({ success: false, error: "Account not found" }) }
      }

      // Update timezone in DB
      const updated = await prisma.account.update({
        where: { id: account.id },
        data: { timeZone }
      })

      // Push to Zoho CRM
      if (account.zohoId) {
        try {
          const token = await getZohoAccessToken()
          const baseUrl = `https://www.zohoapis.${ZOHO_DC}/crm/v3/Accounts`
          await fetch(`${baseUrl}/${account.zohoId}`, {
            method: "PUT",
            headers: {
              Authorization: `Zoho-oauthtoken ${token}`,
              "Content-Type": "application/json"
            },
            body: JSON.stringify({
              data: [
                {
                  Time_Zone: timeZone || ""
                }
              ]
            })
          })
        } catch (syncErr) {
          console.error("Failed to push timezone to Zoho CRM:", syncErr)
        }
      }

      // Log a history note if requested
      const owner = await prisma.user.findUnique({ where: { id: account.ownerId || "" } })
      if (owner) {
        await prisma.note.create({
          data: {
            accountId: account.id,
            authorId: owner.id,
            content: `Customer Timezone changed to "${timeZone || "None"}"${note ? `: ${note}` : ""}`,
            isAutoGenerated: false,
            sentiment: "neutral",
          }
        })
      }

      return {
        statusCode: 200,
        headers: cors,
        body: JSON.stringify({ success: true, account: updated })
      }
    }

    return { statusCode: 405, headers: cors, body: JSON.stringify({ error: "Method not allowed" }) }
  } catch (err: any) {
    console.error("update-account-timezone error:", err)
    return { statusCode: 500, headers: cors, body: JSON.stringify({ success: false, error: err.message }) }
  }
}
