import { authenticateFunction, withFunctionAuth } from "./lib/auth-middleware"
import { Handler } from "@netlify/functions"

import { prisma } from "./lib/prisma"
import { isAdminRole } from "../../src/lib/roles"

const VALID_QUALITIES = ["HOT", "WARM", "COLD", "ON_HOLD", "DO_NOT_CALL", "NEVER_STATUSED"]

const authenticatedHandler: Handler = async (event) => {
  const cors = {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, PATCH, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  }

  if (event.httpMethod === "OPTIONS") return { statusCode: 204, headers: cors, body: "" }

  try {
    if (event.httpMethod === "PATCH" || event.httpMethod === "POST") {
      const sessionUser = await authenticateFunction(event)
      const actorId = sessionUser.dbId || sessionUser.userId
      const body = JSON.parse(event.body || "{}")
      const { accountId, zohoId, quality, note } = body

      if (!quality || !VALID_QUALITIES.includes(quality)) {
        return {
          statusCode: 400,
          headers: cors,
          body: JSON.stringify({ success: false, error: `Invalid quality. Must be one of: ${VALID_QUALITIES.join(", ")}` })
        }
      }

      // Find account by zohoId or internal id
      let account = null
      if (zohoId) {
        account = await prisma.account.findUnique({ where: { zohoId } })
      }
      if (!account && accountId) {
        account = await prisma.account.findUnique({ where: { id: accountId } })
      }

      if (!account) {
        return { statusCode: 404, headers: cors, body: JSON.stringify({ success: false, error: "Account not found" }) }
      }

      if (!isAdminRole(sessionUser.role) && account.ownerId !== actorId) {
        return { statusCode: 403, headers: cors, body: JSON.stringify({ success: false, error: "You can only update your own accounts" }) }
      }

      // Update quality in DB
      const updated = await prisma.account.update({
        where: { id: account.id },
        data: { quality }
      })

      // Log a history note if requested
      const actor = actorId ? await prisma.user.findUnique({ where: { id: actorId } }) : null
      if (actor) {
        await prisma.note.create({
          data: {
            accountId: account.id,
            authorId: actor.id,
            content: `Customer Quality status changed to "${quality}"${note ? `: ${note}` : ""}`,
            isAutoGenerated: false,
            sentiment: "neutral",
          }
        })

        // Push Note to Zoho CRM
        if (account.zohoId) {
          const { pushZohoNote } = await import("./lib/zoho-auth")
          await pushZohoNote(account.zohoId, `Account Quality Updated`, `Customer Quality status changed to "${quality}"${note ? `: ${note}` : ""}`)
        }
      }

      return {
        statusCode: 200,
        headers: cors,
        body: JSON.stringify({ success: true, account: updated })
      }
    }

    return { statusCode: 405, headers: cors, body: JSON.stringify({ error: "Method not allowed" }) }
  } catch (err: any) {
    console.error("update-account-quality error:", err)
    return { statusCode: 500, headers: cors, body: JSON.stringify({ success: false, error: err.message }) }
  }
}

export const handler = withFunctionAuth(authenticatedHandler)
