import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function POST(req: Request, context: { params: Promise<{ accountId: string }> }) {
  try {
    const params = await context.params
    const { accountId } = params

    const body = await req.json().catch(() => ({}))
    const { userId, userEmail } = body

    let authorId = userId
    if (!authorId && userEmail) {
      const user = await prisma.user.findUnique({ where: { email: userEmail } })
      if (user) authorId = user.id
    }
    if (!authorId) {
      const firstAdmin = await prisma.user.findFirst({ where: { role: { contains: "ADMIN", mode: "insensitive" } } })
      if (firstAdmin) authorId = firstAdmin.id
    }

    const now = new Date()

    // Update account with lastClosedCycleAt
    const updatedAccount = await prisma.account.update({
      where: { id: accountId },
      data: { lastClosedCycleAt: now }
    })

    // Log a system note for audit trail
    if (authorId) {
      await prisma.note.create({
        data: {
          accountId: accountId,
          authorId: authorId,
          content: `🔒 [SALE CYCLE CLOSED] Sale cycle closed. Active text conversation window reset for new deal cycle.`,
          isAutoGenerated: true
        }
      }).catch(err => console.warn("Failed to create cycle close note:", err))
    }

    return NextResponse.json({
      success: true,
      lastClosedCycleAt: now.toISOString(),
      account: updatedAccount
    })
  } catch (error: any) {
    console.error('Error closing sale cycle:', error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}
