import assert from 'node:assert/strict'
import fs from 'node:fs'
const scheduler = fs.readFileSync('netlify/functions/bounded-books-auto-sync.ts', 'utf8')
const route = fs.readFileSync('src/app/api/admin/bounded-books-import/route.ts', 'utf8')
const page = fs.readFileSync('src/app/admin/bounded-books-import/page.tsx', 'utf8')
assert.match(scheduler, /BOUNDED_BOOKS_AUTO_SYNC_(STARTED|COMPLETE|SKIPPED|FAILED)/)
assert.match(scheduler, /triggerType: 'SCHEDULED'/)
assert.match(scheduler, /durationMs/)
assert.match(route, /take: 25/)
assert.match(route, /enabled/)
assert.match(route, /requireAdministrator/)
assert.match(page, /Run safe update now/)
assert.match(page, /no-store/)
assert.doesNotMatch(scheduler, /method:\s*['"](POST|PUT|PATCH|DELETE)/)
assert.doesNotMatch(scheduler, /Full Sync|reconciliation.*Apply/i)
console.log('AUTO_SYNC_OBSERVABILITY=PASS')
console.log('AUTO_SYNC_HISTORY=PASS')
console.log('AUTO_SYNC_STATUS_AUTH=PASS')
console.log('AUTO_SYNC_SANITIZED_LOGS=PASS')
console.log('AUTO_SYNC_NO_WRITES_TO_ZOHO=PASS')
