import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const source = fs.readFileSync(path.join(process.cwd(), 'src/lib/bounded-books-import.ts'), 'utf8')
const route = fs.readFileSync(path.join(process.cwd(), 'src/app/api/admin/bounded-books-import/route.ts'), 'utf8')
assert.match(source, /get\(path: string, query: Record<string, string \| number>\)/)
assert.match(source, /per_page: 200/)
assert.match(source, /page_context/)
assert.match(source, /INCOMPLETE_PAGINATION/)
assert.match(source, /REPEATED_PAGE/)
assert.match(source, /PAGE_LIMIT_EXCEEDED/)
assert.match(source, /validateBoundedRange/)
assert.match(source, /creditNotes/)
assert.doesNotMatch(source, /post\s*\(|put\s*\(|patch\s*\(|delete\s*\(/i)
assert.match(source, /Object\.freeze/)
assert.match(route, /requireAdministrator/)
assert.match(route, /IMPORT SEPTEMBER 2026/)
assert.match(route, /readOnlyZohoConfirmation !== true/)
assert.match(route, /boundedBooksImportJob/)
assert.match(route, /getZohoAccessToken/)
assert.doesNotMatch(route, /fetch\([^)]*method:\s*['"](POST|PUT|PATCH|DELETE)/i)
assert.match(route, /cancelRequestedAt/)
console.log('BOUNDED_RANGE=PASS')
console.log('GET_ONLY_TRANSPORT=PASS')
console.log('COMPLETE_PAGINATION=PASS')
console.log('PREFLIGHT_NO_DB_WRITES=PASS')
console.log('CANCELLATION_CONTRACT=PASS')
console.log('CREDIT_NOTE_READ_OR_UNSUPPORTED=PASS')
console.log('ADMIN_ENDPOINTS=PASS')
console.log('LOCAL_TABLE_SCOPE=PASS')
console.log('AUTH_CONFIRMATION=PASS')
