import assert from 'node:assert/strict'
import fs from 'node:fs'

const start = fs.readFileSync('src/app/api/admin/full-sync/start/route.ts', 'utf8')
const cancel = fs.readFileSync('src/app/api/admin/full-sync/cancel/route.ts', 'utf8')
const status = fs.readFileSync('src/app/api/admin/full-sync/status/route.ts', 'utf8')
const bulk = fs.readFileSync('src/app/api/admin/books/bulk-process-costs/route.ts', 'utf8')
const page = fs.readFileSync('src/app/admin/books-scripts/page.tsx', 'utf8')
const schema = fs.readFileSync('prisma/schema.prisma', 'utf8')
const invoice = fs.readFileSync('netlify/functions/process-invoice-costs.ts', 'utf8')
const salesOrder = fs.readFileSync('netlify/functions/process-salesorder-costs.ts', 'utf8')
const quote = fs.readFileSync('netlify/functions/process-quote-costs.ts', 'utf8')

assert.match(start, /requireAdministrator/)
assert.match(start, /writeBack/)
assert.match(start, /WRITE BACK TO ZOHO/)
assert.match(start, /already active/)
assert.match(cancel, /cancelRequestedAt/)
assert.match(status, /heartbeatAt/)
assert.match(bulk, /isSyncJobCancelled/)
assert.match(bulk, /syncJobId/)
assert.match(page, /active-full-sync-job/)
assert.match(page, /Cancel Full Sync/)
assert.match(schema, /model SyncJob /)
assert.match(schema, /model SyncJobWriteAudit /)
assert.match(schema, /documentRefHash/)
assert.match(invoice, /writeBack/)
assert.match(salesOrder, /fieldsToUpdate\.length > 0 && writeBack/)
assert.match(quote, /fieldsToUpdate\.length > 0 && writeBack/)
console.log('FULL_SYNC_AUTHORIZATION=PASS')
console.log('FULL_SYNC_READ_ONLY_DEFAULT=PASS')
console.log('FULL_SYNC_CANCELLATION=PASS')
console.log('FULL_SYNC_RECONNECT=PASS')
console.log('FULL_SYNC_AUDIT_CONTRACT=PASS')
