import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const schema = fs.readFileSync(path.join(root, 'prisma/schema.prisma'), 'utf8')
const auth = fs.readFileSync(path.join(root, 'src/lib/auth.ts'), 'utf8')
const roles = fs.readFileSync(path.join(root, 'src/lib/roles.ts'), 'utf8')
const provision = fs.readFileSync(path.join(root, 'scripts/provision-master-admin.mjs'), 'utf8')
const rotate = fs.readFileSync(path.join(root, 'scripts/rotate-master-admin-password.mjs'), 'utf8')
const migration = fs.readFileSync(path.join(root, 'prisma/migrations/20260914170000_local_master_admin_security/migration.sql'), 'utf8')
const usersEndpoint = fs.readFileSync(path.join(root, 'netlify/functions/get-users.ts'), 'utf8')

assert.match(schema, /authType\s+String\s+@default\("ZOHO"\)/)
assert.match(schema, /isSalesperson\s+Boolean\s+@default\(true\)/)
assert.match(schema, /model AuthAuditEvent/)
assert.match(schema, /model DelegatedSession/)
assert.match(auth, /CredentialsProvider\(/)
assert.match(auth, /role: "MASTER_ADMIN", authType: "LOCAL"/)
assert.match(auth, /bcrypt\.compare\(/)
assert.match(auth, /LOCAL_LOGIN_FAILURE/)
assert.match(roles, /isMasterAdminRole/)
assert.match(roles, /isSalespersonUser/)
assert.match(usersEndpoint, /isSalesperson: true/)
assert.match(auth, /exactMaster/)
assert.match(auth, /failedLoginCount/)
assert.match(auth, /lockedUntil/)
assert.match(auth, /mustRotatePassword/)
assert.doesNotMatch(provision, /console\.log\([^)]*password/i)
assert.doesNotMatch(rotate, /console\.log\([^)]*password/i)
assert.match(migration, /ADD COLUMN IF NOT EXISTS "authType"/)
assert.match(migration, /CREATE TABLE IF NOT EXISTS "AuthAuditEvent"/)
assert.match(migration, /CREATE TABLE IF NOT EXISTS "DelegatedSession"/)
assert.doesNotMatch(migration, /^\s*(DROP|TRUNCATE|DELETE|UPDATE)\b/im)
console.log('MASTER_ADMIN_AUTH_CONTRACT=PASS')
console.log('MASTER_ADMIN_REDACTION=PASS')
console.log('MASTER_ADMIN_DELEGATION_AUDIT=PASS')
