import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const auth = fs.readFileSync(path.join(root, 'netlify/functions/lib/zoho-auth.ts'), 'utf8');
assert.doesNotMatch(auth, /zoho-token-provider/);
assert.match(auth, /export async function getZohoAccessToken\(forceRefresh = false\)/);
assert.match(auth, /ZOHO_DC = cleanEnv\(process\.env\.ZOHO_DC\) \|\| 'com'/);
const sql = fs.readFileSync(path.join(root, 'prisma/migrations/20260914150000_production_schema_alignment/migration.sql'), 'utf8');
assert.ok(sql.includes('ADD COLUMN IF NOT EXISTS "internetMessageId" TEXT'));
assert.doesNotMatch(sql, /\b(DROP|TRUNCATE|DELETE|UPDATE)\b/i);
console.log('AUTH_KNOWN_GOOD_COMPATIBILITY=PASS');
console.log('DATABASE_RECOVERY_MIGRATION=PASS');
