import assert from 'node:assert/strict';
import { buildCatalogCostSources } from '../reconciliation-cost-sources.mjs';
import { runReconciliationCore } from '../reconciliation-engine-core.mjs';
const catalog = buildCatalogCostSources([{ id: 'internal-1', sku: 'SKU-1', name: 'Product One', catalogCost: 17.5, price: 99 }]);
const priceOnly = buildCatalogCostSources([{ id: 'price-only', sku: 'SKU-P', name: 'Price Only', price: 999 }]);
assert.equal(priceOnly.catalogById.size, 0, 'selling price must never become catalog cost');
const result = runReconciliationCore({ docs: [{ id: 'doc-1', type: 'invoice', date: '2026-01-01', row: {}, lineItems: [{ product_id: 'internal-1', sku: 'SKU-1', item_name: 'Product One', physical: true, catalogCost: catalog.catalogById.get('internal-1') }] }], costSources: { itemById: new Map(), itemMap: new Map(), poMapById: new Map(), poMapBySku: new Map() }, vigByDocument: new Map() });
assert.equal(catalog.catalogById.get('internal-1').source, 'dbCatalogCost');
assert.equal(catalog.catalogById.get('internal-1').lookupKeyType, 'catalogItemId');
assert.equal(result.outcomes[0].kind, 'physical-resolved');
assert.equal(result.outcomes[0].costResolution.source, 'dbCatalogCost');
assert.equal(result.outcomes[0].costResolution.cost, 17.5);
assert.equal(result.outcomes[0].costResolution.sourceRecordId, 'internal-1');
assert.equal(result.outcomes[0].costResolution.lookupKeyType, 'catalogItemId');
assert.equal(result.lineAccounting.selectedButUnresolvedCount, 0);
assert.equal(result.outcomes[0].costResolution.effectiveDate, null);
console.log('DB_CATALOG_FALLBACK=PASS');
console.log('NO_SELLING_PRICE_AS_COST=PASS');
console.log('RESOLVED_PROVENANCE_COMPLETE=PASS');
