import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const source = await fs.readFile(new URL('../run-production-reconciliation.ps1', import.meta.url), 'utf8');
const start = source.indexOf("if ($DbPreflightOnly)");
const branch = source.slice(start, start + 3000);
assert.match(branch, /-v.*:\/workspace:ro/);
assert.match(branch, /cp -a \/workspace\/\. \/tmp\/reconciliation-db-work/);
assert.match(branch, /cd \/tmp\/reconciliation-db-work && npm ci/);
assert.doesNotMatch(branch, /cd \/workspace\s*&&\s*npm/);
assert.match(branch, /DB_DEPENDENCIES=PASS/); assert.match(branch, /DB_PRISMA_GENERATE=PASS/); assert.match(branch, /DB_PREFLIGHT=PASS/);
assert.ok((source.match(/DATABASE_URL=/g)||[]).length>=2); assert.match(branch, /--env-file/); assert.doesNotMatch(branch, /Set-Content[^\n]*NoNewline/);
assert.match(source, /\$firstCode\s*=\s*\[int\]\[char\]\$value\[0\]/); assert.match(source, /\$lastCode\s*=\s*\[int\]\[char\]\$value\[\$value\.Length - 1\]/);
assert.match(source, /DB_URL_MISMATCHED_QUOTES/); assert.doesNotMatch(branch, /\[Uri\]/); assert.match(branch, /Set-Content[^\n]*DATABASE_URL=\$databaseUrl/);
assert.match(source, /DB_URL_UNRESOLVED_TEMPLATE/);
const zipStage = source.slice(source.indexOf("-Stage 'zip-smoke'"), source.indexOf("-Stage 'preflight-container'"));
assert.doesNotMatch(zipStage, /\/work\/tmp|tmp\/reconciliation/);
assert.match(zipStage, /node \/work\/reconciliation-zip-smoke\.mjs/);
assert.match(zipStage, /'--network','none'/);
assert.doesNotMatch(zipStage, /apt-get/);
assert.match(zipStage, /command -v unzip/);
assert.doesNotMatch(source, /\/work\/tmp/);
assert.match(source, /'-e','RECONCILIATION_APP_ROOT=\/work'/);
assert.match(await fs.readFile(new URL('./db-structure.test.mjs', import.meta.url), 'utf8'), /process\.env\.RECONCILIATION_APP_ROOT/);
assert.match(await fs.readFile(new URL('./db-structure.test.mjs', import.meta.url), 'utf8'), /schemaPath/);
console.log('DB_WRAPPER_STRUCTURE=PASS');
