import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import { APPLY_LIMITS, assertApplyDisabled, executeReadyApply, validateReadyApplyArtifacts } from '../reconciliation-ready-apply.mjs';

const allowlist = new Set(['cf_vig', 'cf_commission']);
const item = (id, value = 1) => ({ documentType: 'invoice', documentId: id, customFields: [{ apiName: 'cf_vig', value }] });
const rollback = id => ({ documentType: 'invoice', documentId: id, customFields: [{ apiName: 'cf_vig', value: 0 }] });
const base = (forward, back) => ({ summary: { dryRunComplete: true, status: 'COMPLETE_WITH_BLOCKERS', readyPayloadIsolation: true, blockedDocumentExclusion: true }, forward, rollback: back, payloadReview: { pass: true }, unresolved: { documents: [{ documentType: 'invoice', documentId: 'blocked' }] }, uncertain: { documents: [{ documentType: 'invoice', documentId: 'uncertain' }] } });

const one = item('ready'); const oneBack = rollback('ready');
validateReadyApplyArtifacts({ ...base([one], [oneBack]), allowlist, expectedCount: 1 });
assert.throws(() => validateReadyApplyArtifacts({ ...base([one, item('blocked')], [oneBack, rollback('blocked')]), allowlist, expectedCount: 2 }), /APPLY_BLOCKED_DOCUMENT_OVERLAP/);
assert.throws(() => validateReadyApplyArtifacts({ ...base([one, item('second')], [oneBack, rollback('other')]), allowlist, expectedCount: 2 }), /APPLY_ROLLBACK_PAIRING_MISMATCH/);
assert.throws(() => validateReadyApplyArtifacts({ ...base([{ ...one, customFields: [{ apiName: 'native_field', value: 1 }] }], [oneBack]), allowlist, expectedCount: 1 }), /APPLY_FORBIDDEN_FIELD/);
assert.throws(() => assertApplyDisabled({ apply: true }), /APPLY_REMAINS_DISABLED/);
assert.equal(APPLY_LIMITS.canary, 10); assert.equal(APPLY_LIMITS.batch, 25);

const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ready-apply-')); const checkpointPath = path.join(dir, 'checkpoint.json');
const client = { state: new Map([['ready', [{ apiName: 'cf_vig', value: 0 }]]]), reads: 0, writes: 0, async read(row) { this.reads++; return { customFields: this.state.get(row.documentId) }; }, async update(row, fields) { this.writes++; this.state.set(row.documentId, fields); } };
const report = await executeReadyApply({ plan: { eligible: [one], rollback: [oneBack] }, client, outputDir: dir, mode: 'canary', allowlist, checkpointPath, authorization: true });
assert.equal(report.verified, 1); assert.equal(report.failed, 0); assert.equal(client.writes, 1); assert.equal((await fs.readFile(path.join(dir, 'verified-rollback-manifest.json'), 'utf8')).includes('ready'), false);
assert.equal((await fs.stat(checkpointPath)).isFile(), true);
const staleClient = { async read() { return { customFields: [{ apiName: 'cf_vig', value: 9 }] }; }, async update() { throw new Error('must not write stale'); } };
const stale = await executeReadyApply({ plan: { eligible: [one], rollback: [oneBack] }, client: staleClient, outputDir: dir, mode: 'canary', allowlist, checkpointPath: path.join(dir, 'checkpoint-stale.json'), authorization: true });
assert.equal(stale.skippedStale, 1);
await assert.rejects(() => executeReadyApply({ plan: { eligible: [one], rollback: [oneBack] }, client, outputDir: dir, mode: 'resume', allowlist, checkpointPath: path.join(dir, 'checkpoint-resume.json'), authorization: true }), /APPLY_CANARY_VERIFICATION_REQUIRED/);
await fs.writeFile(path.join(dir, 'canary-verification.json'), JSON.stringify({ status: 'PASS', mode: 'canary' }));
const resume = await executeReadyApply({ plan: { eligible: [one], rollback: [oneBack] }, client, outputDir: dir, mode: 'resume', allowlist, checkpointPath, canaryVerificationPath: path.join(dir, 'canary-verification.json'), authorization: true });
assert.equal(resume.verified, 0);
await assert.rejects(() => executeReadyApply({ plan: { eligible: [one], rollback: [oneBack] }, client: { organizationId: 'wrong', read: async () => ({}), update: async () => {} }, outputDir: dir, mode: 'canary', allowlist, checkpointPath: path.join(dir, 'checkpoint-org.json'), authorization: true, expectedOrganizationId: 'expected' }), /ORGANIZATION_MISMATCH/);
let attempts = 0;
const rateLimited = { organizationId: 'expected', async read() { return { customFields: [{ apiName: 'cf_vig', value: attempts ? 1 : 0 }] }; }, async update(row, fields) { attempts++; if (attempts === 1) { const error = new Error('rate'); error.code = 'RATE_LIMIT'; throw error; } } };
const retryReport = await executeReadyApply({ plan: { eligible: [one], rollback: [oneBack] }, client: rateLimited, outputDir: dir, mode: 'canary', allowlist, checkpointPath: path.join(dir, 'checkpoint-retry.json'), authorization: true, expectedOrganizationId: 'expected' });
assert.equal(retryReport.verified, 1); assert.equal(attempts, 2);
let mismatchReads = 0; const mismatchClient = { async read() { mismatchReads++; return { customFields: [{ apiName: 'cf_vig', value: mismatchReads === 1 ? 0 : 999 }] }; }, async update() {} };
const mismatchReport = await executeReadyApply({ plan: { eligible: [one], rollback: [oneBack] }, client: mismatchClient, outputDir: dir, mode: 'canary', allowlist, checkpointPath: path.join(dir, 'checkpoint-mismatch.json'), authorization: true });
assert.equal(mismatchReport.failed, 1);
await fs.rm(dir, { recursive: true, force: true });
console.log('READY_APPLY_CONTRACT=PASS');
console.log('BLOCKED_DOCUMENT_WRITE_IMPOSSIBLE=PASS');
console.log('STALE_SOURCE_PROTECTION=PASS');
console.log('CANARY_LIMIT=PASS');
console.log('BATCH_LIMIT=PASS');
console.log('CHECKPOINT_RESUME=PASS');
console.log('POST_WRITE_VERIFICATION=PASS');
console.log('ROLLBACK_MANIFEST=PASS');
console.log('APPLY_AUDIT_REDACTION=PASS');
console.log('APPLY_NOT_EXECUTED=PASS');
