INSERT INTO "CallScript" ("id", "name", "callType", "department", "scenario", "objective", "content", "discoveryPrompts", "objectionResponses", "closingPrompt", "priority", "isActive", "createdAt", "updatedAt")
SELECT 'titan-default-sales-coach', 'Account relationship call', 'Follow-up', 'SALES', 'FOLLOW_UP', 'Understand the current job, solve the next purchasing need, and agree on one concrete next step',
'Hi {{ContactName}}, this is your Titan Diamond representative. I was reviewing {{AccountName}} and wanted to check how the last products performed and what work you have coming up. I can help you match the right tool to the job and put together the next order or quote while we are on the phone.',
'["What materials and equipment are you using on the next job?", "What is slowing the crew down or costing the most right now?", "What sizes and quantities will you need, and by when?", "Who else should be involved in the decision?"]'::jsonb,
'[{"trigger":"Your price is too high","response":"That makes sense to compare. Let us compare cost per cut, expected life, downtime, and freight—not just the purchase price—using your actual job conditions."},{"trigger":"We already have a supplier","response":"I am not asking you to disrupt something that works. Let us identify one job where Titan can be benchmarked fairly, then earn the next step from the result."},{"trigger":"I need to think about it","response":"Absolutely. What specifically needs to be resolved—fit, performance, timing, price, or approval—so I can give you the right information instead of chasing you?"}]'::jsonb,
'Based on what you shared, should I build the quote now, place the approved order, or schedule the exact follow-up time?', 80, true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM "CallScript" WHERE "name" = 'Account relationship call');

INSERT INTO "CallScript" ("id", "name", "callType", "department", "scenario", "objective", "content", "discoveryPrompts", "objectionResponses", "closingPrompt", "priority", "isActive", "createdAt", "updatedAt")
SELECT 'titan-default-collections-coach', 'Collections resolution call', 'Collections', 'COLLECTIONS', 'PAYMENT', 'Resolve the balance while preserving the customer relationship and recording a reliable commitment',
'Hi {{ContactName}}, this is Titan Diamond calling about {{AccountName}}. I want to make this easy to resolve. I am reviewing the open balance and would like to understand whether the issue is timing, documentation, a dispute, or something else we can fix today.',
'["Did you receive the invoice and supporting documents?", "Is any amount disputed or waiting on a purchase order?", "What exact amount and date can be committed today?", "Who controls the payment release if it is not you?"]'::jsonb,
'[{"trigger":"We never received the invoice","response":"I can resend it while we are connected and confirm the correct recipient. Once received, what payment date should we record?"},{"trigger":"The order has a problem","response":"Thank you for telling me. I will separate the service issue from the undisputed balance, document the owner, and give you a specific resolution follow-up."},{"trigger":"We cannot pay right now","response":"Let us establish what is possible: a partial payment, a dated commitment, or a manager-reviewed arrangement. What amount and date can you reliably keep?"}]'::jsonb,
'Let me confirm the amount, commitment date, recipient, and the next action so neither side has to repeat this conversation.', 80, true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM "CallScript" WHERE "name" = 'Collections resolution call');

INSERT INTO "CallScript" ("id", "name", "callType", "department", "scenario", "objective", "content", "discoveryPrompts", "objectionResponses", "closingPrompt", "priority", "isActive", "createdAt", "updatedAt")
SELECT 'titan-default-support-coach', 'Customer support resolution', 'Support', 'SUPPORT', 'PROBLEM', 'Understand the issue, protect safety, establish ownership, and give the customer a specific resolution path',
'Hi {{ContactName}}, I have {{AccountName}} open and I am going to take ownership of getting this routed correctly. Please walk me through what happened, what product and equipment were involved, and what outcome you need.',
'["What product or SKU is involved?", "What material, equipment, speed, and operating conditions were used?", "Is there any immediate safety concern?", "Do you have photos, video, lot information, or the document number?", "What would a fair resolution look like?"]'::jsonb,
'[{"trigger":"I want a refund","response":"I understand. I will document the requested outcome and the evidence required for the authorized decision. First, let us confirm the product, order, condition, and what happened."},{"trigger":"I am extremely upset","response":"You have every right to expect a clear answer. I am taking ownership of the next step now; let me repeat the issue back so you do not have to start over."},{"trigger":"This product is dangerous","response":"Stop using the product immediately. I will mark this as a safety escalation and collect only the information needed for the authorized team to respond."}]'::jsonb,
'I have recorded the issue, owner, evidence needed, and next update time. I will not make you restart the story.', 80, true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM "CallScript" WHERE "name" = 'Customer support resolution');

INSERT INTO "CallScript" ("id", "name", "callType", "department", "scenario", "objective", "content", "discoveryPrompts", "objectionResponses", "closingPrompt", "priority", "isActive", "createdAt", "updatedAt")
SELECT 'titan-default-shipping-coach', 'Shipping status and exception', 'Shipping', 'SHIPPING', 'DELIVERY', 'Give a reliable shipment answer, resolve missing information, and establish the next checkpoint',
'Hi {{ContactName}}, I have the {{AccountName}} shipping information in front of me. I am calling to confirm the delivery need and make sure the shipment, address, contact, and timing are correct.',
'["Which order or shipment are we discussing?", "Is the delivery address and site contact correct?", "Is there a hard job deadline or receiving restriction?", "Is the issue carrier movement, damage, shortage, or documentation?"]'::jsonb,
'[{"trigger":"The tracking has not moved","response":"I will verify the last carrier scan and whether an exception case is required. I will give you a specific update time instead of asking you to keep checking."},{"trigger":"The package is damaged","response":"Please keep the packaging and product, take clear photos, and stop using anything unsafe. I will document the shipment and route the claim with the order details attached."},{"trigger":"We received the wrong item","response":"I will verify the ordered, picked, and received SKUs and quantities, then coordinate the authorized replacement or correction without making you repeat the information."}]'::jsonb,
'Let me confirm the address, contact, required date, owner, and exact next update time before we end the call.', 80, true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM "CallScript" WHERE "name" = 'Shipping status and exception');
