import { NextResponse } from 'next/server'
import { authenticateRequest } from '../../../../../netlify/functions/lib/auth-middleware'
import { prisma } from '@/lib/prisma'
import { isAdminRole } from '@/lib/roles'

const headers = { 'Cache-Control': 'private, no-store' }
export async function PATCH(req: Request) {
  let auth
  try { auth = await authenticateRequest(req) } catch { return NextResponse.json({ error: 'Sign in required' }, { status: 401, headers }) }
  let body
  try { body = await req.json() } catch { return NextResponse.json({ error: 'Invalid request' }, { status: 400, headers }) }
  if (!body || typeof body.accountId !== 'string' || !body.accountId ||
    !Object.hasOwn(body, 'cardOnFile') || (body.cardOnFile !== null && typeof body.cardOnFile !== 'boolean')) {
    return NextResponse.json({ error: 'Account and valid card status required' }, { status: 400, headers })
  }
  try {
    const user = await prisma.user.findFirst({ where: { OR: [
      ...(auth.dbId ? [{ id: auth.dbId }] : []), ...(auth.userId ? [{ id: auth.userId }] : []),
      ...(auth.email ? [{ email: { equals: auth.email, mode: 'insensitive' as const } }] : []),
    ] }, select: { id: true, email: true, role: true } })
    if (!user || user.role.toUpperCase() === 'VIEWER') return NextResponse.json({ error: 'Access unavailable' }, { status: 403, headers })
    const manager = await prisma.systemSetting.findUnique({ where: { key: 'collections_manager_id' }, select: { value: true } })
    const company = isAdminRole(user.role) || manager?.value === user.id || user.email.toLowerCase() === 'brian@titandiamond.net'
    const saved = await prisma.$transaction(async tx => {
      const result = await tx.account.updateMany({
        where: { id: body.accountId, ...(company ? {} : { ownerId: user.id }) },
        data: { cardOnFile: body.cardOnFile },
      })
      if (!result.count) return false
      await tx.note.create({ data: {
        accountId: body.accountId, authorId: user.id, isAutoGenerated: false,
        content: `Collections card-on-file status set to ${body.cardOnFile === null ? 'Unknown' : body.cardOnFile ? 'Yes (staff confirmed)' : 'No'}; status only, not payment authorization.`,
      } })
      return true
    })
    if (!saved) return NextResponse.json({ error: 'Account not found or unavailable to you' }, { status: 404, headers })
    return NextResponse.json({ success: true, cardOnFile: body.cardOnFile }, { headers })
  } catch { return NextResponse.json({ error: 'Could not save card status. Please retry.' }, { status: 500, headers }) }
}
