/* eslint-disable react-hooks/set-state-in-effect */
'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  FiAlertTriangle, FiBox, FiCheck, FiCheckCircle, FiChevronRight,
  FiDollarSign, FiFileText, FiLoader, FiMail, FiPackage,
  FiRefreshCw, FiSearch, FiShield, FiTruck, FiUser, FiXCircle,
} from 'react-icons/fi'
import toast from 'react-hot-toast'

type WorkItem = {
  id: string; customer: string; invoiceNumber: string; amount: number; balance: number; profit: number
  date: string; dueDate?: string | null; daysInStage: number; stage: string; rep: string
  documentType: 'salesorder' | 'invoice'; documentStatus: string; salesOrderZohoId?: string | null
  syncConflict?: boolean; pendingCostSync?: boolean; costReady?: boolean; lineCount?: number
}
type LifeDoc = { id:string; zohoId?:string; status?:string; amount?:number; invoiceNumber?:string; items?:Record<string, unknown>; balance?:number }
type PackageDoc = { id:string; zohoId?:string; packageNumber?:string; status?:string; carrier?:string; trackingNumber?:string; shippingCharge?:number; items?:Record<string, unknown> }
type Lifecycle = { salesOrder?:LifeDoc|null; purchaseOrders?:LifeDoc[]; packages?:PackageDoc[]; invoices?:LifeDoc[] }

type Lane = 'exceptions'|'approval'|'fulfillment'|'billing'
const laneMeta: Record<Lane,{label:string;hint:string;color:string}> = {
  exceptions:{label:'Exceptions',hint:'Blocked or needs review',color:'text-red-300'},
  approval:{label:'Approval',hint:'Confirm sales order',color:'text-violet-300'},
  fulfillment:{label:'Fulfillment',hint:'Package and ship',color:'text-cyan-300'},
  billing:{label:'Billing',hint:'Create and send invoice',color:'text-blue-300'},
}
const laneOrder: Lane[] = ['exceptions','approval','fulfillment','billing']

const money = (value:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value||0)
const lower = (value:unknown) => String(value||'').toLowerCase()
// Zoho document dates are calendar dates, not instants. Converting a YYYY-MM-DD
// value to local time moves midnight UTC to the prior day in Arizona.
const dateLabel = (value?:string|null) => {
  if (!value) return '—'
  const match = String(value).match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (match) return `${Number(match[2])}/${Number(match[3])}/${match[1]}`
  const parsed = new Date(value)
  return Number.isNaN(parsed.getTime()) ? '—' : parsed.toLocaleDateString()
}
const docNumber = (doc?:LifeDoc|null) => String(doc?.invoiceNumber || doc?.items?.invoiceNumber || doc?.items?.salesOrderNumber || doc?.items?.salesorder_number || doc?.zohoId || '—')
const asRecord = (value:unknown):Record<string,unknown> => value && typeof value==='object' && !Array.isArray(value) ? value as Record<string,unknown> : {}
const asRows = (value:unknown):Record<string,unknown>[] => Array.isArray(value) ? value.map(asRecord) : []
const firstText = (...values:unknown[]) => String(values.find(value=>value!==undefined&&value!==null&&String(value).trim())||'')
const firstNumber = (...values:unknown[]) => Number(values.find(value=>value!==undefined&&value!==null&&value!=='')||0)||0
const addressText = (value:unknown) => { const row=asRecord(value); return [firstText(row.attention),firstText(row.address,row.street),firstText(row.street2),[firstText(row.city),firstText(row.state),firstText(row.zip,row.zipcode)].filter(Boolean).join(', '),firstText(row.country)].filter(Boolean).join('\n') }

function laneFor(item:WorkItem):Lane {
  if(item.syncConflict || item.pendingCostSync || !item.costReady) return 'exceptions'
  if(item.documentType==='salesorder') return ['draft','pending'].includes(lower(item.documentStatus)) ? 'approval' : 'fulfillment'
  if(lower(item.documentStatus)==='draft') return 'billing'
  return 'billing'
}
function nextAction(item:WorkItem){
  const lane=laneFor(item)
  if(item.syncConflict) return 'Resolve sync conflict'
  if(item.pendingCostSync || !item.costReady) return 'Calculate costs'
  if(item.documentType==='salesorder') return ['draft','pending'].includes(lower(item.documentStatus)) ? 'Confirm sales order' : 'Prepare fulfillment'
  if(lane==='billing') return 'Send invoice'
  return 'Send invoice'
}

function StatusPill({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'good'|'warn'|'bad'|'info'}){
  const styles={neutral:'bg-white/5 text-neutral-300 border-white/10',good:'bg-emerald-500/10 text-emerald-300 border-emerald-500/25',warn:'bg-amber-500/10 text-amber-300 border-amber-500/25',bad:'bg-red-500/10 text-red-300 border-red-500/25',info:'bg-cyan-500/10 text-cyan-300 border-cyan-500/25'}
  return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${styles[tone]}`}>{children}</span>
}
function Step({done,active,label,detail}:{done:boolean;active?:boolean;label:string;detail:string}){
  return <div className="relative flex min-w-[130px] flex-1 items-start gap-2"><div className={`mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full border ${done?'border-emerald-400 bg-emerald-500/20 text-emerald-300':active?'border-orange-400 bg-orange-500/20 text-orange-300':'border-white/10 bg-white/5 text-neutral-600'}`}>{done?<FiCheck size={12}/>:active?<FiChevronRight size={12}/>:<span className="h-1.5 w-1.5 rounded-full bg-current"/>}</div><div><div className={`text-xs font-bold ${done?'text-emerald-200':active?'text-white':'text-neutral-500'}`}>{label}</div><div className="mt-0.5 text-[10px] text-neutral-600">{detail}</div></div></div>
}

export default function ProcessingPage(){
  const [items,setItems]=useState<WorkItem[]>([]); const [selectedId,setSelectedId]=useState(''); const [lifecycle,setLifecycle]=useState<Lifecycle|null>(null)
  const [loading,setLoading]=useState(true); const [detailLoading,setDetailLoading]=useState(false); const [busy,setBusy]=useState('')
  const [lane,setLane]=useState<Lane|'all'>('all'); const [query,setQuery]=useState(''); const [tracking,setTracking]=useState(''); const [carrier,setCarrier]=useState('')

  const load=useCallback(async(keep=true)=>{setLoading(true);try{const res=await fetch('/api/zoho-invoices?view=pipeline',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to load processing queue');const rows:WorkItem[]=data.deals||[];setItems(rows);setSelectedId(current=>keep&&rows.some(x=>x.id===current)?current:(rows[0]?.id||''))}catch(error){toast.error(error instanceof Error?error.message:'Unable to load queue')}finally{setLoading(false)}},[])
  useEffect(()=>{void load(false)},[load])
  const selected=useMemo(()=>items.find(x=>x.id===selectedId)||null,[items,selectedId])
  const counts=useMemo(()=>items.reduce<Record<Lane,number>>((a,x)=>{a[laneFor(x)]++;return a},{exceptions:0,approval:0,fulfillment:0,billing:0}),[items])
  const filtered=useMemo(()=>items.filter(x=>(lane==='all'||laneFor(x)===lane)&&(!query||`${x.customer} ${x.invoiceNumber} ${x.rep}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>{const risk=(x:WorkItem)=>(x.syncConflict?10000:0)+(x.pendingCostSync||!x.costReady?5000:0)+x.daysInStage;return risk(b)-risk(a)}),[items,lane,query])

  const loadLifecycle=useCallback(async(item:WorkItem)=>{setDetailLoading(true);try{const type=item.documentType==='salesorder'?'SalesOrder':'Invoice';const res=await fetch(`/api/document-lifecycle?zohoId=${encodeURIComponent(item.id)}&type=${type}`,{cache:'no-store'});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||'Unable to load lifecycle');setLifecycle(data.lifecycle)}catch(error){setLifecycle(null);toast.error(error instanceof Error?error.message:'Unable to load order details')}finally{setDetailLoading(false)}},[])
  useEffect(()=>{if(selected)void loadLifecycle(selected);else setLifecycle(null)},[selected,loadLifecycle])

  const request=async(key:string,url:string,body:Record<string,unknown>)=>{setBusy(key);try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok||data.success===false||data.error)throw new Error(data.error||data.message||'Action failed');toast.success('Step completed');await load();const updated=items.find(x=>x.id===selectedId);if(updated)await loadLifecycle(updated);return data}catch(error){toast.error(error instanceof Error?error.message:'Action failed');return null}finally{setBusy('')}}
  const updateStatus=(type:'Invoice'|'SalesOrder',action:string,id=selected?.id||'')=>request(action,'/api/zoho-update-status',{documentId:id,type,action,trackingNumber:tracking,shippingMethod:carrier})
  const convert=(sourceType:'SalesOrder',targetType:'Invoice',sourceId=selected?.id||'')=>request(`convert-${targetType}`,'/api/zoho-convert',{sourceType,sourceId,targetType})
  const sendDocument=(type:'SalesOrder'|'Invoice',id:string)=>request('send',type==='Invoice'?'/api/zoho-email-invoice':'/api/zoho-send-document',type==='Invoice'?{invoiceId:id}:{documentId:id,type})
  const processCosts=()=>{if(!selected)return;const endpoint=selected.documentType==='invoice'?'/api/process-invoice-costs':'/api/process-salesorder-costs';const key=selected.documentType==='invoice'?'invoiceId':'salesorderId';return request('costs',endpoint,{[key]:selected.id})}
  const createPackage=async()=>{const so=lifecycle?.salesOrder;const soId=so?.zohoId||selected?.id;if(!soId)return toast.error('No sales order is linked');setBusy('package');try{const getRes=await fetch('/api/zoho-fulfillment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'GetSalesOrder',salesOrderId:soId})});const detail=await getRes.json();if(!getRes.ok||!detail.success)throw new Error(detail.error||detail.message||'Unable to read sales order');const packable=(detail.lineItems||[]).map((x:Record<string,unknown>)=>({lineItemId:x.line_item_id,quantity:Number(x.quantity_to_pack ?? x.quantity_remaining ?? x.quantity ?? 0)})).filter((x:{lineItemId:unknown;quantity:number})=>Boolean(x.lineItemId)&&x.quantity>0);if(!packable.length)throw new Error('No packable line items found');const createRes=await fetch('/api/zoho-fulfillment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'CreatePackage',salesOrderId:soId,items:packable})});const result=await createRes.json();if(!createRes.ok||!result.success)throw new Error(result.error||result.message||'Package creation failed');toast.success('Package prepared in Zoho Books');if(selected)await loadLifecycle(selected)}catch(error){toast.error(error instanceof Error?error.message:'Package creation failed')}finally{setBusy('')}}

  const so=lifecycle?.salesOrder; const invoices=lifecycle?.invoices||[]; const packages=lifecycle?.packages||[];
  const orderData=asRecord(so?.items || invoices[0]?.items)
  const lineItems=asRows(orderData.line_items || orderData.lineItemDetails || orderData.items)
  const customerEmail=firstText(orderData.email,orderData.email_id,orderData.contact_email)
  const customerPhone=firstText(orderData.phone,orderData.phone_number,orderData.contact_phone)
  const shippingAddress=addressText(orderData.shipping_address || orderData.shippingAddress)
  const billingAddress=addressText(orderData.billing_address || orderData.billingAddress)
  const reference=firstText(orderData.reference_number,orderData.referenceNumber)
  const soConfirmed=so?['confirmed','open','invoiced','closed'].includes(lower(so.status)):selected?.documentType==='invoice'
  const packaged=packages.length>0; const shipped=packages.some(x=>Boolean(x.trackingNumber)||['shipped','delivered'].includes(lower(x.status)))
  const hasInvoice=invoices.length>0||selected?.documentType==='invoice'; const Icon=selected?.documentType==='salesorder'?FiPackage:FiDollarSign

  return <div className="page-content min-h-0"><div className="page-header mt-2 gap-4"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.24em] text-orange-400"><FiShield/> Operations command center</div><h1 className="page-title mt-1">Order Processing</h1><p className="page-subtitle">Administrator workflow beginning with converted sales orders.</p></div><button className="td-btn td-btn-ghost" onClick={()=>void load()} disabled={loading}><FiRefreshCw className={loading?'animate-spin':''}/> Refresh live queue</button></div>
    <div className="page-body min-h-0 space-y-4">
      <div className="grid grid-cols-2 gap-2 lg:grid-cols-6">{laneOrder.map(key=><button key={key} onClick={()=>setLane(lane===key?'all':key)} className={`rounded-xl border p-3 text-left transition ${lane===key?'border-orange-400/60 bg-orange-500/10':'border-white/10 bg-white/[.03] hover:bg-white/[.06]'}`}><div className="flex items-center justify-between"><span className={`text-xl font-black ${laneMeta[key].color}`}>{counts[key]}</span>{key==='exceptions'&&counts[key]>0?<FiAlertTriangle className="text-red-400"/>:null}</div><div className="mt-1 text-xs font-black uppercase text-white">{laneMeta[key].label}</div><div className="text-[10px] text-neutral-600">{laneMeta[key].hint}</div></button>)}</div>
      <div className="grid min-h-[680px] gap-4 xl:grid-cols-[390px_minmax(0,1fr)]">
        <aside className="flex min-h-0 flex-col overflow-hidden rounded-2xl border border-white/10 bg-[#0b0e13]"><div className="border-b border-white/10 p-3"><div className="relative"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-600"/><input className="td-input w-full pl-9" placeholder="Customer, document, or rep…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="mt-2 flex items-center justify-between text-[10px] font-bold uppercase text-neutral-600"><span>{lane==='all'?'All active work':laneMeta[lane].label}</span><span>{filtered.length} orders</span></div></div><div className="min-h-0 flex-1 overflow-y-auto">{loading&&!items.length?<div className="grid h-40 place-items-center text-neutral-500"><FiLoader className="animate-spin"/></div>:filtered.map(item=>{const active=item.id===selectedId;const itemLane=laneFor(item);return <button key={`${item.documentType}-${item.id}`} onClick={()=>setSelectedId(item.id)} className={`w-full border-b border-white/5 p-4 text-left transition ${active?'bg-orange-500/10 shadow-[inset_3px_0_0_#f97316]':'hover:bg-white/[.04]'}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="truncate text-sm font-black text-white">{item.customer}</div><div className="mt-1 flex items-center gap-2 text-[11px] text-neutral-500"><span>{item.invoiceNumber}</span><span>•</span><span>{item.documentType==='salesorder'?'SO':'INV'}</span><span>•</span><span>{item.daysInStage}d</span></div></div><div className="text-right"><div className="font-mono text-sm font-bold text-white">{money(item.amount)}</div><div className={`mt-1 text-[9px] font-black uppercase ${laneMeta[itemLane].color}`}>{laneMeta[itemLane].label}</div></div></div><div className="mt-3 flex flex-wrap gap-1.5">{item.syncConflict&&<StatusPill tone="bad"><FiXCircle/> Sync conflict</StatusPill>}{(item.pendingCostSync||!item.costReady)&&<StatusPill tone="warn"><FiAlertTriangle/> Costs</StatusPill>}{!item.syncConflict&&item.costReady&&<StatusPill tone="good"><FiCheck/> Costed</StatusPill>}</div><div className="mt-3 flex items-center justify-between text-xs"><span className="font-semibold text-neutral-300">{nextAction(item)}</span><FiChevronRight className={active?'text-orange-400':'text-neutral-700'}/></div></button>})}{!loading&&!filtered.length&&<div className="p-10 text-center text-sm text-neutral-600">No work matches this view.</div>}</div></aside>
        <main className="min-w-0 overflow-hidden rounded-2xl border border-white/10 bg-[#0b0e13]">{!selected?<div className="grid h-full place-items-center text-neutral-600">Select an order to begin.</div>:<><div className="border-b border-white/10 bg-gradient-to-r from-orange-500/[.08] to-transparent p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl border border-orange-500/25 bg-orange-500/10 text-orange-300"><Icon size={20}/></div><div><div className="text-xl font-black text-white">{selected.customer}</div><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-neutral-500"><span>{selected.invoiceNumber}</span><span>•</span><span>{selected.rep}</span><span>•</span><span>{selected.lineCount||0} lines</span><span>•</span><span>{dateLabel(selected.date)}</span></div></div></div><div className="text-right"><div className="font-mono text-2xl font-black text-white">{money(selected.amount)}</div><div className="text-xs text-neutral-500">{money(selected.profit)} profit</div></div></div><div className="mt-5 flex gap-3 overflow-x-auto pb-1"><Step done={soConfirmed} active={!soConfirmed} label="Sales order" detail={so?lower(so.status):'not created'}/><Step done={shipped} active={soConfirmed&&!shipped} label="Fulfillment" detail={shipped?'shipped':packaged?'package ready':'not packaged'}/><Step done={hasInvoice} active={shipped&&!hasInvoice} label="Invoice" detail={hasInvoice?'created':'not created'}/></div></div>
          {detailLoading?<div className="grid h-80 place-items-center text-neutral-500"><FiLoader className="animate-spin"/></div>:<div className="grid gap-4 p-4 2xl:grid-cols-[minmax(0,1fr)_330px]"><div className="space-y-4">
            {(selected.syncConflict||selected.pendingCostSync||!selected.costReady)&&<section className="rounded-xl border border-red-500/25 bg-red-500/[.06] p-4"><div className="flex items-center gap-2 font-black text-red-200"><FiAlertTriangle/> Release blockers</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{selected.syncConflict&&<div className="rounded-lg border border-red-500/20 bg-black/20 p-3 text-xs"><b className="text-red-200">SYNC CONFLICT</b><p className="mt-1 text-neutral-400">Zoho and the portal both changed. Resolve before overwriting.</p></div>}{(selected.pendingCostSync||!selected.costReady)&&<div className="rounded-lg border border-amber-500/20 bg-black/20 p-3 text-xs"><b className="text-amber-200">FINANCIALS NOT READY</b><p className="mt-1 text-neutral-400">Dead cost, profit, and commission require calculation.</p><button onClick={()=>void processCosts()} disabled={!!busy} className="td-btn td-btn-sm td-btn-primary mt-3">{busy==='costs'?<FiLoader className="animate-spin"/>:<FiDollarSign/>} Calculate costs</button></div>}</div></section>}
            <section className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center justify-between"><div><h2 className="font-black text-white">Recommended next move</h2><p className="mt-1 text-xs text-neutral-500">Actions unlock as the order advances.</p></div><StatusPill tone="info">{laneMeta[laneFor(selected)].label}</StatusPill></div><div className="mt-4 grid gap-3 sm:grid-cols-2">
              {so&&!soConfirmed&&<button onClick={()=>void updateStatus('SalesOrder','confirm',so.zohoId)} disabled={!!busy} className="td-btn td-btn-primary justify-center"><FiCheckCircle/> Confirm sales order</button>}
              {so&&soConfirmed&&!packaged&&<button onClick={()=>void createPackage()} disabled={!!busy} className="td-btn td-btn-primary justify-center"><FiBox/> Prepare full package</button>}
              {so&&packaged&&!shipped&&<div className="sm:col-span-2 rounded-xl border border-cyan-500/20 bg-cyan-500/[.05] p-3"><div className="text-xs font-black text-cyan-200">RECORD SHIPMENT</div><div className="mt-2 grid gap-2 sm:grid-cols-2"><input className="td-input" placeholder="Carrier / method" value={carrier} onChange={e=>setCarrier(e.target.value)}/><input className="td-input" placeholder="Tracking number" value={tracking} onChange={e=>setTracking(e.target.value)}/></div><button onClick={()=>void updateStatus('SalesOrder','shipped',so.zohoId)} disabled={!!busy||!tracking.trim()} className="td-btn td-btn-primary mt-2 w-full justify-center"><FiTruck/> Mark shipped</button></div>}
              {so&&soConfirmed&&!hasInvoice&&<button onClick={()=>void convert('SalesOrder','Invoice',so.zohoId)} disabled={!!busy} className="td-btn td-btn-ghost justify-center"><FiFileText/> Create draft invoice</button>}
              {hasInvoice&&invoices.some(x=>lower(x.status)==='draft')&&<button onClick={()=>void sendDocument('Invoice',(invoices.find(x=>lower(x.status)==='draft')||invoices[0]).zohoId||selected.id)} disabled={!!busy} className="td-btn td-btn-primary justify-center"><FiMail/> Send invoice</button>}
              {!hasInvoice&&selected.documentType==='salesorder'&&<button onClick={()=>void sendDocument('SalesOrder',selected.id)} disabled={!!busy} className="td-btn td-btn-ghost justify-center"><FiMail/> Email current document</button>}
            </div></section>
            <section className="overflow-hidden rounded-xl border border-white/10 bg-white/[.025]"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><h2 className="font-black text-white">Order contents</h2><p className="mt-1 text-xs text-neutral-500">Items, quantities, rates, and totals used to process this order.</p></div><StatusPill>{lineItems.length} lines</StatusPill></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-black/30 text-[10px] uppercase tracking-wider text-neutral-500"><tr><th className="px-4 py-3">Item</th><th className="px-3 py-3">SKU</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3 text-right">Rate</th><th className="px-4 py-3 text-right">Total</th></tr></thead><tbody>{lineItems.map((line,index)=>{const qty=firstNumber(line.quantity);const rate=firstNumber(line.rate,line.price);return <tr key={firstText(line.line_item_id,line.item_id,index)} className="border-t border-white/5"><td className="px-4 py-3"><div className="font-bold text-white">{firstText(line.name,line.item_name,line.description)||'Unnamed item'}</div></td><td className="px-3 py-3 font-mono text-neutral-400">{firstText(line.sku,line.item_sku)||'—'}</td><td className="px-3 py-3 text-right font-mono">{qty}</td><td className="px-3 py-3 text-right font-mono">{money(rate)}</td><td className="px-4 py-3 text-right font-mono font-bold text-white">{money(firstNumber(line.item_total,line.itemTotal,line.total)||qty*rate)}</td></tr>})}{!lineItems.length&&<tr><td colSpan={5} className="p-8 text-center text-neutral-600">No local line-item detail is available.</td></tr>}</tbody></table></div></section>
            <section className="rounded-xl border border-white/10 bg-white/[.025] p-4"><h2 className="font-black text-white">Customer & delivery</h2><div className="mt-4 grid gap-4 text-xs md:grid-cols-3"><div><div className="text-[10px] font-black uppercase text-neutral-600">Contact</div><div className="mt-2 font-bold text-white">{selected.customer}</div><div className="mt-1 text-neutral-400">{customerEmail||'No email stored'}</div><div className="mt-1 text-neutral-400">{customerPhone||'No phone stored'}</div></div><div><div className="text-[10px] font-black uppercase text-neutral-600">Ship to</div><div className="mt-2 whitespace-pre-line leading-5 text-neutral-300">{shippingAddress||'No shipping address stored'}</div></div><div><div className="text-[10px] font-black uppercase text-neutral-600">Bill to / reference</div><div className="mt-2 whitespace-pre-line leading-5 text-neutral-400">{billingAddress||'No billing address stored'}</div><div className="mt-2 text-neutral-300">PO / Ref: {reference||'—'}</div></div></div></section>
            <section className="rounded-xl border border-white/10 bg-white/[.025] p-4"><h2 className="font-black text-white">Linked records</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{packages.map(pkg=><div key={pkg.id} className="rounded-lg border border-white/10 bg-black/20 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold"><FiBox className="text-cyan-400"/> {pkg.packageNumber||'PACKAGE'}</div><StatusPill tone={pkg.trackingNumber?'good':'warn'}>{pkg.status||'pending'}</StatusPill></div><div className="mt-2 text-xs text-neutral-500">{pkg.carrier||'Carrier not set'} {pkg.trackingNumber?`• ${pkg.trackingNumber}`:''}</div></div>)}{invoices.map(inv=><div key={inv.id} className="rounded-lg border border-white/10 bg-black/20 p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold"><FiFileText className="text-blue-400"/> INV #{docNumber(inv)}</div><StatusPill tone="info">{inv.status||'draft'}</StatusPill></div><div className="mt-2 flex justify-between text-xs text-neutral-500"><span>Invoice total</span><span className="font-mono text-neutral-300">{money(Number(inv.amount||0))}</span></div></div>)}{!packages.length&&!invoices.length&&<div className="md:col-span-2 rounded-lg border border-dashed border-white/10 p-8 text-center text-sm text-neutral-600">No package or invoice records yet. Use the recommended action above.</div>}</div></section>
          </div><aside className="space-y-4"><section className="rounded-xl border border-white/10 bg-white/[.025] p-4"><h3 className="text-xs font-black uppercase tracking-wider text-neutral-400">Order control</h3><div className="mt-3 space-y-3 text-xs"><div className="flex justify-between"><span className="text-neutral-500">Document status</span><b className="uppercase text-white">{selected.documentStatus}</b></div><div className="flex justify-between"><span className="text-neutral-500">Age in stage</span><b>{selected.daysInStage} days</b></div><div className="flex justify-between"><span className="text-neutral-500">Cost calculation</span><b className={selected.costReady?'text-emerald-300':'text-amber-300'}>{selected.costReady?'READY':'REQUIRED'}</b></div><div className="flex justify-between"><span className="text-neutral-500">Sync health</span><b className={selected.syncConflict?'text-red-300':'text-emerald-300'}>{selected.syncConflict?'CONFLICT':'CLEAR'}</b></div></div></section><section className="rounded-xl border border-white/10 bg-white/[.025] p-4"><h3 className="text-xs font-black uppercase tracking-wider text-neutral-400">Financial snapshot</h3><div className="mt-3 space-y-3"><div className="flex justify-between text-sm"><span className="text-neutral-500">Order value</span><b className="font-mono">{money(selected.amount)}</b></div><div className="flex justify-between text-sm"><span className="text-neutral-500">Profit</span><b className="font-mono text-emerald-300">{money(selected.profit)}</b></div></div></section><section className="rounded-xl border border-white/10 bg-white/[.025] p-4"><h3 className="text-xs font-black uppercase tracking-wider text-neutral-400">Ownership</h3><div className="mt-3 flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-white/5 text-neutral-400"><FiUser/></div><div><div className="text-sm font-bold text-white">{selected.rep}</div><div className="text-[10px] text-neutral-600">Assigned representative</div></div></div></section></aside></div>}
        </>}</main>
      </div>
    </div>
  </div>
}