/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { FiCheckCircle, FiCreditCard, FiRefreshCw, FiTruck } from 'react-icons/fi'
import toast from 'react-hot-toast'

type WorkItem = { id:string; customer:string; invoiceNumber:string; amount:number; balance:number; date:string; daysInStage:number; stage:string; rep:string; documentType?:string; documentStatus?:string; salesOrderZohoId?:string|null }

const stageInfo: Record<string,{label:string;color:string}> = {
  billing:{label:'DRAFT INVOICES TO SEND',color:'text-blue-300'}, estimate:{label:'ESTIMATES TO APPROVE',color:'text-purple-300'}, salesorder:{label:'SALES ORDERS TO APPROVE',color:'text-cyan-300'},
  invoiced:{label:'PAYMENTS TO COLLECT',color:'text-amber-300'}, partially_paid:{label:'PARTIAL PAYMENTS',color:'text-orange-300'},
  overdue:{label:'OVERDUE COLLECTIONS',color:'text-red-300'}, shipping:{label:'READY TO SHIP',color:'text-emerald-300'}, needs_gift:{label:'PAID — FULFILLMENT CHECK',color:'text-emerald-300'}, complete:{label:'COMPLETE',color:'text-neutral-400'}
}

export default function ProcessingPage(){
  const [items,setItems]=useState<WorkItem[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const [selected,setSelected]=useState<WorkItem|null>(null); const [tracking,setTracking]=useState(''); const [payment,setPayment]=useState('')
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/zoho-invoices?view=pipeline',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load work');setItems((d.deals||[]).map((x:WorkItem)=>x.documentType==='invoice'&&String(x.documentStatus||'').toLowerCase()==='draft'?{...x,stage:'billing'}:x.documentType==='salesorder'&&['confirmed','open'].includes(String(x.documentStatus||'').toLowerCase())?{...x,stage:'shipping'}:x))}catch(e:any){toast.error(e.message)}finally{setLoading(false)}},[])
  useEffect(()=>{load()},[load])
  const groups=useMemo(()=>items.filter(x=>x.stage!=='complete').reduce<Record<string,WorkItem[]>>((a,x)=>{(a[x.stage]||=[]).push(x);return a},{}),[items])
  const run=async(action:'approve'|'ship'|'pay')=>{if(!selected)return;setBusy(action);try{let url='',body:any={};if(action==='approve'){url='/api/zoho-update-status';body={documentId:selected.id,type:selected.stage==='billing'?'Invoice':selected.stage==='estimate'?'Quote':'SalesOrder',action:selected.stage==='billing'?'sent':selected.stage==='estimate'?'accepted':'confirm'}}else if(action==='ship'){if(!tracking.trim())throw new Error('Enter a tracking number');const orderId=selected.documentType==='invoice'?selected.salesOrderZohoId:selected.id;if(!orderId)throw new Error('This paid invoice is not linked to a sales order');url='/api/zoho-update-status';body={documentId:orderId,type:'SalesOrder',action:'shipped',trackingNumber:tracking.trim()}}else{const amount=Number(payment||selected.balance);if(!amount||amount<=0)throw new Error('Enter a payment amount');url='/api/zoho-payment';body={invoiceId:selected.id,amount,paymentMethod:'Check / Other',paymentDate:new Date().toISOString().slice(0,10)}}const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||d.success===false||d.error)throw new Error(d.error||d.message||'Action failed');toast.success('Task completed');setSelected(null);setTracking('');setPayment('');await load()}catch(e:any){toast.error(e.message)}finally{setBusy('')} }
  const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0)
  return <div className="page-content"><div className="page-header mt-2"><div><h1 className="page-title">Order Processing Center</h1><p className="page-subtitle">Approve, fulfill, ship, and collect without leaving this screen</p></div><button className="td-btn td-btn-ghost" onClick={load}><FiRefreshCw className={loading?'animate-spin':''}/> Refresh</button></div>
    <div className="page-body space-y-5"><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{Object.entries(groups).map(([stage,rows])=><button key={stage} onClick={()=>document.getElementById(stage)?.scrollIntoView({behavior:'smooth'})} className="glass-panel rounded-xl p-4 text-left border border-white/10"><div className={`text-2xl font-black ${stageInfo[stage]?.color||'text-white'}`}>{rows.length}</div><div className="text-[10px] font-bold text-neutral-500 mt-1">{stageInfo[stage]?.label||stage.toUpperCase()}</div></button>)}</div>
    {loading?<div className="py-20 text-center text-neutral-500">Building the live work queue…</div>:Object.entries(groups).map(([stage,rows])=><section id={stage} key={stage} className="glass-panel rounded-2xl border border-white/10 overflow-hidden"><div className="px-5 py-4 border-b border-white/10 flex justify-between"><h2 className={`font-black text-sm ${stageInfo[stage]?.color||'text-white'}`}>{stageInfo[stage]?.label||stage.toUpperCase()}</h2><span className="text-xs text-neutral-500">{rows.length} NEED ACTION</span></div><div className="divide-y divide-white/5">{rows.map(x=><button key={x.id} onClick={()=>{setSelected(x);setPayment(String(x.balance||x.amount))}} className="w-full px-5 py-4 grid grid-cols-[1fr_auto] md:grid-cols-[1.5fr_1fr_1fr_auto] gap-4 items-center text-left hover:bg-white/5"><div><div className="font-bold text-white">{x.customer}</div><div className="text-xs text-neutral-500">#{x.invoiceNumber} · {x.rep}</div></div><div className="hidden md:block text-sm text-neutral-400">{x.daysInStage} days waiting</div><div className="hidden md:block font-mono text-sm">{money(x.balance||x.amount)}</div><span className="td-btn td-btn-sm td-btn-primary">Process</span></button>)}</div></section>)}</div>
    {selected&&<div className="fixed inset-0 z-[100] bg-black/75 flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="w-full max-w-xl rounded-2xl bg-[#111318] border border-white/15 shadow-2xl p-6"><div className="flex justify-between"><div><div className="text-xs text-orange-400 font-black">COMPLETE TASK</div><h2 className="text-xl font-black mt-1">{selected.customer}</h2><p className="text-sm text-neutral-500">#{selected.invoiceNumber} · {money(selected.balance||selected.amount)}</p></div><button onClick={()=>setSelected(null)} className="text-neutral-400">✕</button></div>
      {(['billing','estimate','salesorder'].includes(selected.stage))&&<button disabled={!!busy} onClick={()=>run('approve')} className="td-btn td-btn-primary w-full mt-6 justify-center"><FiCheckCircle/> {busy?'Processing…':selected.stage==='billing'?'Send Invoice':selected.stage==='estimate'?'Approve Estimate':'Approve Sales Order'}</button>}
      {['shipping','needs_gift'].includes(selected.stage)&&<><label className="block text-xs font-bold text-neutral-400 mt-6 mb-2">TRACKING NUMBER</label><input value={tracking} onChange={e=>setTracking(e.target.value)} className="td-input w-full" placeholder="Enter carrier tracking number"/><button disabled={!!busy} onClick={()=>run('ship')} className="td-btn td-btn-primary w-full mt-3 justify-center"><FiTruck/> {busy?'Processing…':'Mark Shipped & Complete'}</button></>}
      {['invoiced','partially_paid','overdue'].includes(selected.stage)&&<><label className="block text-xs font-bold text-neutral-400 mt-6 mb-2">PAYMENT AMOUNT</label><input type="number" step="0.01" value={payment} onChange={e=>setPayment(e.target.value)} className="td-input w-full"/><button disabled={!!busy} onClick={()=>run('pay')} className="td-btn td-btn-primary w-full mt-3 justify-center"><FiCreditCard/> {busy?'Recording…':'Record Payment'}</button><p className="text-xs text-neutral-500 mt-3">Records the payment in Zoho Books and immediately updates the local invoice balance and status.</p></>}
    </div></div>}</div>
}
