"use client"
import { useEffect, useState } from 'react'
export function VoiceManagement() {
  const [users, setUsers] = useState<any[]>([]), [numbers, setNumbers] = useState<any[]>([])
  const [detail, setDetail] = useState<any>(null), [fields, setFields] = useState<any>({})
  const [replaceNumbers, setReplaceNumbers] = useState(false), [assignments, setAssignments] = useState<string[]>([])
  const [editableNumbers, setEditableNumbers] = useState<string[]>([])
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [notice, setNotice] = useState('')
  async function load() { setBusy(true); try { const r = await fetch('/api/admin/voice'); const d = await r.json(); if (!r.ok) throw Error(d.error); setUsers(d.users); setNumbers(d.numbers); setError('') } catch(e) { setError(String(e)) } finally { setBusy(false) } }
  useEffect(() => { void load() }, [])
  async function edit(id: string) { setBusy(true); try { const r = await fetch('/api/admin/voice?userId=' + id); const d = await r.json(); if (!r.ok) throw Error(d.error); setDetail(d); setFields({ name: d.user.name, emailid: d.user.emailid, timezone: d.user.timezone, lang: d.user.lang, departmentName: d.user.departmentName, extension: d.user.extension, zvtRole: d.user.zvtRole }); setAssignments(d.numbers.map((n: any) => n.numberMapId)); setReplaceNumbers(false); setEditableNumbers([]); setError('') } catch(e) { setError(String(e)) } finally { setBusy(false) } }
  async function save(action: string) {
    if (!window.confirm(`${action === 'delete' ? 'Permanently delete' : action === 'create' ? 'Create' : 'Update'} Zoho Voice user ${fields.name} (${fields.emailid})?${replaceNumbers ? '\nReplace number access with exactly the selected numbers and editing permissions below.' : ''}`)) return
    setBusy(true); setNotice(''); try {
      const r = await fetch('/api/admin/voice', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, confirmed: true, requestId: crypto.randomUUID(), userId: detail?.user?.userid, revision: detail?.revision, fields: action === 'delete' ? {} : { ...fields, ...(replaceNumbers ? { associatedNumbers: assignments.map(numberMapId => ({ numberMapId, allowNumberEdit: editableNumbers.includes(numberMapId) })) } : {}) } }) })
      const d = await r.json(); if (!r.ok || !d.success) throw Error(d.error); setDetail(null); setNotice('Zoho confirmed the change and the user list was refreshed.'); await load()
    } catch(e) { setError(String(e)); setDetail(null) } finally { setBusy(false) }
  }
  const inputClass = 'w-full p-2 rounded border border-white/15 bg-slate-950'
  return <section className="p-4 border border-white/10 rounded-xl space-y-4">
    <div className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-bold">Zoho Voice users and numbers</h2><div className="flex gap-3"><button disabled={busy} onClick={() => void load()}>Refresh</button><button disabled={busy} onClick={() => { setDetail({ create: true }); setFields({ name: '', emailid: '', timezone: 'America/Phoenix', lang: 'en', departmentName: '', zvtRole: 5 }); setReplaceNumbers(false); setAssignments([]) }}>Add user</button><a href="https://voice.zoho.com/app/zvt.jsp#/phoneconfig/list" target="_blank" rel="noreferrer">Number capabilities ↗</a></div></div>
    <p className="text-xs text-neutral-400">Live Zoho assignments refresh in the phone every minute and when the app regains focus. SMS activation, number purchases and call routing are managed in Zoho Voice; its public number API does not expose those settings. SMS/MMS and carrier registration must be enabled by Zoho.</p>
    {error && <p role="alert" className="text-amber-300 break-words">{error}</p>}{notice && <p role="status">{notice}</p>}
    <div className="grid sm:grid-cols-2 gap-2">{users.map(u => <button className="text-left p-3 bg-white/5 rounded" key={u.userid} disabled={busy} onClick={() => void edit(u.userid)}><strong>{u.name}</strong><span className="block text-xs">{u.emailid} · {u.zvtRoleName} · Ext {u.extension || '—'}</span></button>)}</div>
    {detail && <div className="space-y-3 border border-cyan-500/30 p-3 rounded"><h3>{detail.create ? 'New Voice user' : 'Edit Voice user'}</h3><div className="grid sm:grid-cols-2 gap-3">{[['name', 'Name'], ['emailid', 'Email'], ['timezone', 'Timezone'], ['lang', 'Language'], ['departmentName', 'Department'], ['extension', 'Extension']].map(([key, label]) => <label key={key}>{label}<input className={inputClass} value={fields[key] ?? ''} onChange={e => setFields({ ...fields, [key]: e.target.value })} /></label>)}<label>Role<select className={inputClass} value={fields.zvtRole} onChange={e => setFields({ ...fields, zvtRole: Number(e.target.value) })}>{[[1,'Admin'],[2,'Technician'],[3,'Supervisor'],[4,'Supervisor Plus'],[5,'Telephony Agent']].map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select></label></div>
      {[3, 4].includes(Number(fields.zvtRole)) && <label>Supervised agents<select multiple className={inputClass} value={fields.associatedAgents || detail.user?.associatedAgents || []} onChange={e => setFields({ ...fields, associatedAgents: Array.from(e.target.selectedOptions, o => o.value) })}>{users.filter(u => u.userid !== detail.user?.userid).map(u => <option key={u.agentId} value={u.agentId}>{u.name}</option>)}</select></label>}
      {detail.user?.canChangeModerator && <label><input type="checkbox" checked={fields.isModerator ?? detail.user?.isModerator ?? false} onChange={e => setFields({ ...fields, isModerator: e.target.checked })} /> Moderator access</label>}
      <label className="flex gap-2"><input type="checkbox" checked={replaceNumbers} onChange={e => setReplaceNumbers(e.target.checked)} />Replace this user’s assigned numbers and number-editing permissions</label>
      {replaceNumbers && <><p className="text-xs text-amber-200">Review the entire selection. Unchecked numbers will be removed. Existing number-editing permissions are not returned by the API; explicitly select every permission to keep.</p><div className="max-h-64 overflow-auto space-y-2">{numbers.map(n => <div key={n.id} className="flex flex-wrap justify-between gap-2"><label><input type="checkbox" checked={assignments.includes(n.numberMapId)} onChange={e => setAssignments(e.target.checked ? [...assignments, n.numberMapId] : assignments.filter(id => id !== n.numberMapId))} /> {n.label} · {n.number}</label><label><input disabled={!assignments.includes(n.numberMapId)} type="checkbox" checked={editableNumbers.includes(n.numberMapId)} onChange={e => setEditableNumbers(e.target.checked ? [...editableNumbers, n.numberMapId] : editableNumbers.filter(id => id !== n.numberMapId))} /> Allow editing</label></div>)}</div></>}
      <div className="flex gap-4"><button disabled={busy} className="bg-cyan-700 p-2 rounded" onClick={() => void save(detail.create ? 'create' : 'update')}>Review and save</button>{!detail.create && <button disabled={busy} className="text-red-300" onClick={() => void save('delete')}>Delete user…</button>}<button disabled={busy} onClick={() => setDetail(null)}>Cancel</button></div>
    </div>}
    <details><summary>{numbers.length} live numbers</summary><div className="max-h-72 overflow-auto">{numbers.map(n => <p key={n.id} className="p-2 border-b border-white/10">{n.label} · {n.number} · {n.active ? 'Active' : 'Inactive'}<span className="block text-xs text-neutral-400">SMS capability checked by Zoho when sending</span></p>)}</div></details>
  </section>
}
