import fs from "node:fs"; import path from "node:path"; import { describe, expect, it } from "vitest"
const root = process.cwd(); const read = (file: string) => fs.readFileSync(path.join(root, file), "utf8")
describe("durable campaign recovery contracts", () => {
  it("keeps GET status read-only", () => { const source = read("netlify/functions/campaign-job-status.ts"); expect(source).not.toMatch(/sendZoho|fetch\(`https:\/\/voice|\.update\(|\.create\(/) })
  it("claims atomically and distinguishes pre-send and post-send expiry", () => { const source = read("netlify/functions/lib/campaign-worker.ts"); expect(source).toContain("FOR UPDATE SKIP LOCKED"); expect(source).toContain('state: "AMBIGUOUS"'); expect(source).toContain('state: "PENDING"') })
  it("never gives the quarantined legacy job recipient rows or resume", () => { const migration = read("prisma/migrations/20260922230000_durable_campaign_recovery/migration.sql"); const api = read("src/app/api/admin/campaign-recovery/route.ts"); expect(migration).toContain("cmud3ggj9000311xvyygo6aje"); expect(migration).not.toMatch(/INSERT INTO "CampaignRecipient"/); expect(api).toContain("Quarantined campaigns require a separate reviewed campaign") })
  it("records SENDING before provider fetch and has no automatic retry loop", () => { const source = read("netlify/functions/lib/campaign-worker.ts"); expect(source.indexOf('state: "SENDING"')).toBeLessThan(source.indexOf("await fetch")); expect(source).not.toMatch(/retry|setTimeout/) })
  it("preserves MMS multipart and browser-independent watchdog", () => { expect(read("netlify/functions/lib/campaign-worker.ts")).toContain("buildZohoSmsFormData"); expect(read("netlify.toml")).toContain('[functions."campaign-recovery-watchdog"]') })
  it("reconciles overdue receipts without sending a probe", () => { const source = read("netlify/functions/campaign-delivery-reconciliation.ts"); expect(source).toContain("REVIEW_READY"); expect(source).not.toContain("fetch("); expect(source).not.toContain("campaignRecipient.update") })
  it("requires explicit ambiguous review and prevents legal override", () => { expect(read("src/app/api/admin/campaign-recovery/route.ts")).toContain("RETRY AMBIGUOUS RECIPIENT"); expect(read("src/app/api/admin/phone-deliverability/route.ts")).toContain('"OPT_OUT_SUPPRESSED", "LEGAL_SUPPRESSED"') })
  it("does not suppress legacy missing results", () => { const migration = read("prisma/migrations/20260922230000_durable_campaign_recovery/migration.sql"); expect(migration).not.toContain('INSERT INTO "PhoneDeliverability"') })
})
