const fs = require("fs")
const { parse } = require("csv-parse/sync")
const { PrismaClient } = require("@prisma/client")

const prisma = new PrismaClient()

async function main() {
  console.log("Starting backfill for call logs...")

  // Load all users
  const users = await prisma.user.findMany()
  const userMap = new Map() // By lowercase name
  users.forEach(u => {
    if (u.name) userMap.set(u.name.toLowerCase().trim(), u.id)
  })

  // Load all contacts for phone matching
  const contacts = await prisma.contact.findMany({ select: { accountId: true, phone: true, mobilePhone: true } })
  const phoneToAccountId = new Map()
  contacts.forEach(c => {
    if (c.phone) phoneToAccountId.set(c.phone.replace(/\D/g, ''), c.accountId)
    if (c.mobilePhone) phoneToAccountId.set(c.mobilePhone.replace(/\D/g, ''), c.accountId)
  })

  const path = "C:/Users/titan/Documents/Titan Diamond/AUTOMATIONS/exports/call_logs_2019-01-01_00_00_2026-06-12_23_59.csv"
  const rawFile = fs.readFileSync(path, "utf8")
  
  // Find the header row
  const lines = rawFile.split(/\r?\n/)
  let startIndex = 0
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].startsWith("Log ID,Call Type")) {
      startIndex = i
      break
    }
  }

  const csvContent = lines.slice(startIndex).join("\n")
  const records = parse(csvContent, { columns: true, skip_empty_lines: true, relax_quotes: true })

  console.log(`Parsed ${records.length} call logs.`)

  // Batch execution
  async function processInBatches(items, batchSize, processItem) {
    for (let i = 0; i < items.length; i += batchSize) {
      const batch = items.slice(i, i + batchSize)
      await Promise.all(batch.map(processItem))
      console.log(`Processed ${Math.min(i + batchSize, items.length)} / ${items.length} calls`)
    }
  }

  let countNotes = 0
  await processInBatches(records, 100, async (row) => {
    const logId = row["Log ID"]
    const agentName = row["Agent"]
    const callTime = row["Call Time"]
    const duration = row["Duration"]
    const callStatus = row["Call Status"]
    const description = row["Call Description"]
    
    if (!logId) return

    let authorId = userMap.get((agentName || "").toLowerCase().trim())
    if (!authorId) {
      const admin = users.find(u => u.email === "ben@titandiamond.net")
      authorId = admin ? admin.id : users[0].id
    }

    // Try to find account by phone
    const extractPhone = (str) => {
        const match = str.match(/\+?\d+/)
        return match ? match[0].replace(/\D/g, '') : null
    }

    const sourcePhone = extractPhone(row["Source"])
    const destPhone = extractPhone(row["Destination"])

    let accountId = null
    if (sourcePhone && phoneToAccountId.has(sourcePhone)) accountId = phoneToAccountId.get(sourcePhone)
    if (!accountId && destPhone && phoneToAccountId.has(destPhone)) accountId = phoneToAccountId.get(destPhone)

    // Fallback: search account by name if it was in parens e.g. (WOODY MOORE)
    if (!accountId) {
      const extractName = (str) => {
          const match = str.match(/\((.*?)\)/)
          return match ? match[1] : null
      }
      const sourceName = extractName(row["Source"])
      const destName = extractName(row["Destination"])
      const nameToSearch = sourceName || destName
      if (nameToSearch) {
         const acc = await prisma.account.findFirst({
           where: { name: { contains: nameToSearch, mode: "insensitive" } }
         })
         if (acc) accountId = acc.id
      }
    }

    if (!accountId) {
       // If no account could be matched, we can't create a Note easily. 
       // For now, we skip it, or log it to an unassigned account. We'll skip for data integrity unless we have an Unassigned account.
       return
    }

    // Upsert note
    // We don't have an @unique constraint on callSid, so we must findFirst
    const existingNote = await prisma.note.findFirst({
        where: { callSid: logId }
    })
    
    if (!existingNote) {
        let content = `Call: ${callStatus}`
        if (description) content += ` - ${description}`
        content += ` (Duration: ${duration})`
        
        await prisma.note.create({
            data: {
                accountId: accountId,
                authorId: authorId,
                content: content,
                callSid: logId,
                sentiment: "Neutral",
                isAutoGenerated: true,
                createdAt: new Date(callTime),
                updatedAt: new Date(callTime)
            }
        })
        countNotes++
    }
  })

  console.log(`Backfill complete. Inserted ${countNotes} call logs as notes.`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
