const fs = require("fs")
const { parse } = require("csv-parse/sync")
const { PrismaClient } = require("@prisma/client")

const prisma = new PrismaClient()

async function main() {
  console.log("Starting backfill for SMS logs...")

  // Load all users
  const users = await prisma.user.findMany()
  const userMap = new Map() // By lowercase name
  users.forEach(u => {
    if (u.name) userMap.set(u.name.toLowerCase().trim(), u.id)
  })

  // Load all contacts for phone matching
  const contacts = await prisma.contact.findMany({ select: { accountId: true, phone: true, mobilePhone: true } })
  const phoneToAccountId = new Map()
  contacts.forEach(c => {
    if (c.phone) phoneToAccountId.set(c.phone.replace(/\D/g, ''), c.accountId)
    if (c.mobilePhone) phoneToAccountId.set(c.mobilePhone.replace(/\D/g, ''), c.accountId)
  })

  const path = "C:/Users/titan/Documents/Titan Diamond/AUTOMATIONS/exports/sms_log_csv_2024-11-01_00_00_2026-06-12_23_59.csv"
  const rawFile = fs.readFileSync(path, "utf8")
  
  // Find the header row
  const lines = rawFile.split(/\r?\n/)
  let startIndex = 0
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].startsWith("Log Id,Direction")) {
      startIndex = i
      break
    }
  }

  const csvContent = lines.slice(startIndex).join("\n")
  const records = parse(csvContent, { columns: true, skip_empty_lines: true, relax_quotes: true })

  console.log(`Parsed ${records.length} SMS logs.`)

  // Batch execution
  async function processInBatches(items, batchSize, processItem) {
    for (let i = 0; i < items.length; i += batchSize) {
      const batch = items.slice(i, i + batchSize)
      await Promise.all(batch.map(processItem))
      console.log(`Processed ${Math.min(i + batchSize, items.length)} / ${items.length} SMS`)
    }
  }

  let countNotes = 0
  await processInBatches(records, 100, async (row) => {
    const logId = row["Log Id"]
    const direction = row["Direction"]
    const agentName = row["Agent"]
    const callTime = row["Time"]
    const message = row["Message"]
    
    if (!logId) return

    let authorId = userMap.get((agentName || "").toLowerCase().trim())
    if (!authorId) {
      const admin = users.find(u => u.email === "ben@titandiamond.net")
      authorId = admin ? admin.id : users[0].id
    }

    const extractPhone = (str) => {
        const match = str.match(/\+?\d+/)
        return match ? match[0].replace(/\D/g, '') : null
    }

    const sourcePhone = extractPhone(row["From"])
    const destPhone = extractPhone(row["To"])

    let accountId = null
    // If incoming, "From" is the customer. If outgoing, "To" is the customer.
    if (direction === "INCOMING" && sourcePhone && phoneToAccountId.has(sourcePhone)) accountId = phoneToAccountId.get(sourcePhone)
    if (direction === "OUTGOING" && destPhone && phoneToAccountId.has(destPhone)) accountId = phoneToAccountId.get(destPhone)
    
    if (!accountId && sourcePhone && phoneToAccountId.has(sourcePhone)) accountId = phoneToAccountId.get(sourcePhone)
    if (!accountId && destPhone && phoneToAccountId.has(destPhone)) accountId = phoneToAccountId.get(destPhone)

    if (!accountId) {
      const extractName = (str) => {
          const match = str.match(/\((.*?)\)/)
          return match ? match[1] : null
      }
      const sourceName = extractName(row["From"])
      const destName = extractName(row["To"])
      const nameToSearch = direction === "INCOMING" ? sourceName : destName
      if (nameToSearch && !nameToSearch.includes("+1")) {
         const acc = await prisma.account.findFirst({
           where: { name: { contains: nameToSearch, mode: "insensitive" } }
         })
         if (acc) accountId = acc.id
      }
    }

    if (!accountId) return

    const existingNote = await prisma.note.findFirst({
        where: { callSid: logId }
    })
    
    if (!existingNote) {
        let content = `SMS ${direction}: ${message}`
        
        await prisma.note.create({
            data: {
                accountId: accountId,
                authorId: authorId,
                content: content,
                callSid: logId, // Store log id here for deduplication
                sentiment: "Neutral",
                isAutoGenerated: true,
                createdAt: new Date(callTime),
                updatedAt: new Date(callTime)
            }
        })
        countNotes++
    }
  })

  console.log(`Backfill complete. Inserted ${countNotes} SMS logs as notes.`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
