const fs = require('fs');
const path = 'src/components/SalesCallCampaignModal.tsx';
let data = fs.readFileSync(path, 'utf8');

const replacement = `const contactName = currentAccount?.contacts?.[0]?.firstName || "there";
      const accountAddress = currentAccount?.shippingAddress?.street || currentAccount?.billingAddress?.street || "your location";

      const pitches = {
        medusa: \`Let me tell you about one of my best selling blades for the kind of work you are doing. It's called 'The Medusa'. What my customers all love about this new blade is that it has a 12mm jumbo segment compared to most blades on the market that are just 10mm, giving you longer blade life. This new blade is perfect for cured concrete, brick, block, stone & pavers. Another great feature that makes it one of the best blades on the market for the money is the segments are made under a higher heat and a lower pressure which makes the diamonds last longer without sacrificing speed. Each one of the segments are laser welded for reliability and safety, and the core is speed tensioned to eliminate warping and wobbling. Now \${contactName}, retail stores in your city would sell a blade of this quality for $150 bucks all day long! I normally wholesale it for $100 bucks! Right now, like I said, we are giving this blade away for FREE! The way the promotion works is I send 6 blades out there; the first blade you pull out of the box is absolutely FREE! No matter how you feel about it! The other 5 blades are only $68 bucks each! If you do the math, you're getting 6 blades for $340 bucks! That's less than $57 bucks per blade! And at that price you're stealing them! Now to get these 6 blades in your hands... are you still out there at \${accountAddress}?\`,
        kingTurbo: \`Let me tell you about one of my best blades for what you are doing... it's called 'The King Turbo Blade'. What my customers all love about this new blade is that it has 24 serrated turbo segments which makes the blade cut super fast and super smooth through hard re-enforced concrete and other hard materials. \${contactName}, this premium soft bond blade will actually pull itself through the cut, so you don't have to put a lot of pressure on the saw, you just let the blade do the work for you. The other thing they have done with this new blade that makes it one of the best on the market is they form the diamond segments differently; they make them under a higher heat and a lower pressure which makes the diamonds last longer without sacrificing speed. Now \${contactName}, retail stores will sell a blade of this quality for $250 bucks all day long! I normally wholesale it for $175 bucks! Right now, like I said, we are giving this blade away for FREE! The way the promotion works is I send three blades out there... the first blade you pull out of the box is absolutely FREE! No matter how you feel about it! The other two are only $175.00 bucks each! If you do the math you're getting three blades for $350.00 bucks! That's $116 bucks per blade! And at that price you're stealing them! Now to get these three blades in your hands... are you still out there at \${accountAddress}?\`,
        titan: \`I want to tell you about one of my best blades for what you're doing. It's called 'The Titan'. This brand-new blade is designed to work great on a handheld or a walk-behind saw. It's versatile enough to cut everything from re-enforced concrete, asphalt, ductile iron, re-enforced concrete pipe and even rebar! Honestly \${contactName}, there is nothing this blade can't cut! The major improvement over other blades on the market is when they make the diamond segments, they make them under a higher heat and a lower pressure which makes the diamonds last longer without sacrificing any speed, so you will definitely get your money's worth when it comes to blade life. On top of all that, The Titan has a speed tensioned cobalt core which prevents warping and wobbling, and the segments are laser welded for reliability and safety! My customers are telling me that this is the best blade they've ever used, hands down! I don't expect you to take my word for it; I'll prove it to you! \${contactName}, if you were able to find a blade of this quality at your local supplier it would cost $400 or more! I normally wholesale these blades for $299 each! Right now I am giving you one absolutely free of charge. What I do is send you out my starter pack; the first blade you pull out of the box is absolutely free! The other two blades in the box are only $250 each! If you do the math, you're getting three blades for $500.00 bucks which is only $166 bucks per blade! And at that price you're stealing them! Now to get these three blades in your hands... are you still out there at \${accountAddress}?\`,
        darkKnight: \`I want to tell you about one of my best blades for what you're doing. It's called my 'Dark Knight Blade'. This brand-new blade is designed to work great on a handheld or a walk-behind saw. It's versatile enough to cut everything from re-enforced concrete to asphalt, to brick, block & stone. Honestly \${contactName}, there is nothing this blade can't cut! The major improvement over other blades on the market is when they make the diamond segments; they make them under a higher heat and a lower pressure which makes the diamonds last longer without sacrificing any speed, so you will definitely get your money's worth when it comes to blade life. On top of all that, the Dark Knight Blade has a speed tensioned cobalt core which prevents warping and wobbling, and the segments are laser welded for reliability and safety! My customers are telling me that this is the best blade they've ever used, hands down! I don't expect you to take my word for it; I'll prove it to you! \${contactName}, if you were able to find a blade of this quality at your local supplier it would cost $250 or more! I normally wholesale these blades for $175 each! Right now I am giving you one absolutely free of charge. What I'm gonna do is send you out my starter pack... the first blade you pull out of the box is absolutely free! The other 3 blades in the box are only $150 each! If you do the math, you're getting 4 blades for $450.00 bucks which is less than $113 bucks per blade! And at that price you're stealing them! Now to get these 4 blades in your hands... are you still out there at \${accountAddress}?\`,
        razor: \`We have a brand new line up that we field tested against dozens of other manufacturers. Our new line of blades not only cut faster, but in most cases lasted twice as long as the competition. With this early release, our manufacturer gave us blades to give away free to our new customers to kick-start new relationships! \${contactName}, this blade is ideal for cutting ceramic tile, marble, granite & even porcelain and it cuts through it like a hot knife through butter! The new 'Razor Blade' has a reinforced core to prevent warping, wobbling and walking and runs super quiet. This blade cuts really clean & fast & the manufacturer claims 100% chip free cutting. My customers told me that this is the best 10" blade they ever used, I don't expect you to take my word for it... I'll prove it to you! Now \${contactName}, retail stores would sell a blade of this quality for $150 bucks all day long! I normally wholesale it for $120 bucks! Right now, we are giving this blade away for FREE! The way the promotion works is I send four blades out there... the first blade you pull out of the box is absolutely FREE! The next three are only $100 each! Now to get these new Razor Blades in your hands, what's the best address to ship them to? Is it still \${accountAddress}?\`,
        generic: \`With direct-from-manufacturer pricing and higher quality products, we only offer the best of the best based upon your application.\`
      };`;

data = data.replace(/const pitches = \{[\s\S]*?generic: `.*?`\n\s*\};/g, replacement);
data = data.replace(/const pitches = \{[\s\S]*?generic: ".*?"\n\s*\};/g, replacement);

fs.writeFileSync(path, data);
console.log('Done.');
