import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { checkAccountOwnership } from "@/lib/auth-helpers"

type TimelineEvent = {
  id: string
  accountId: string
  contactId: string | null
  actorId: string | null
  channel: string
  direction: string | null
  eventType: string
  sourceType: string
  sourceId: string
  subject: string | null
  summary: string | null
  occurredAt: Date
  metadata: unknown
  createdAt: Date
  contact: { id: string; firstName: string | null; lastName: string | null } | null
  actor: { id: string; name: string | null } | null
}

const clipped = (value: string | null | undefined) => value ? value.slice(0, 1000) : null

export async function GET(req: Request, { params }: { params: Promise<{ accountId: string }> }) {
  const { accountId } = await params
  const access = await checkAccountOwnership(accountId)
  if (!access.authorized) return access.errorResponse

  const account = await prisma.account.findFirst({
    where: { OR: [{ id: accountId }, { zohoId: accountId }] },
    select: { id: true },
  })
  if (!account) return NextResponse.json({ success: false, error: "Account not found" }, { status: 404 })

  const url = new URL(req.url)
  const limit = Math.min(Math.max(Number(url.searchParams.get("limit")) || 100, 1), 250)
  const before = url.searchParams.get("before")
  const beforeDate = before ? new Date(before) : null
  if (beforeDate && Number.isNaN(beforeDate.getTime())) {
    return NextResponse.json({ success: false, error: "Invalid before date" }, { status: 400 })
  }

  const dateFilter = beforeDate ? { lt: beforeDate } : undefined
  const [indexed, notes, messages, calls, emails] = await Promise.all([
    prisma.communicationEvent.findMany({
      where: { accountId: account.id, ...(dateFilter ? { occurredAt: dateFilter } : {}) },
      include: { contact: { select: { id: true, firstName: true, lastName: true } }, actor: { select: { id: true, name: true } } },
      orderBy: [{ occurredAt: "desc" }, { id: "desc" }],
      take: limit,
    }),
    prisma.note.findMany({
      where: { accountId: account.id, ...(dateFilter ? { createdAt: dateFilter } : {}) },
      include: { author: { select: { id: true, name: true } } },
      orderBy: { createdAt: "desc" },
      take: limit,
    }),
    prisma.smsMessage.findMany({
      where: { accountId: account.id, ...(dateFilter ? { createdAt: dateFilter } : {}) },
      include: { contact: { select: { id: true, firstName: true, lastName: true } }, author: { select: { id: true, name: true } } },
      orderBy: { createdAt: "desc" },
      take: limit,
    }),
    prisma.callLog.findMany({
      where: { accountId: account.id, ...(dateFilter ? { createdAt: dateFilter } : {}) },
      include: { contact: { select: { id: true, firstName: true, lastName: true } }, author: { select: { id: true, name: true } } },
      orderBy: { createdAt: "desc" },
      take: limit,
    }),
    prisma.email.findMany({
      where: {
        accountId: account.id,
        ...(beforeDate ? { OR: [{ sentAt: { lt: beforeDate } }, { receivedAt: { lt: beforeDate } }, { createdAt: { lt: beforeDate } }] } : {}),
      },
      orderBy: { createdAt: "desc" },
      take: limit,
    }),
  ])

  const emailUserIds = [...new Set(emails.map(email => email.userId).filter((id): id is string => Boolean(id)))]
  const emailUsers = emailUserIds.length ? await prisma.user.findMany({ where: { id: { in: emailUserIds } }, select: { id: true, name: true } }) : []
  const emailUserMap = new Map(emailUsers.map(user => [user.id, user]))

  const historical: TimelineEvent[] = [
    ...notes.map(note => ({
      id: `note-${note.id}`, accountId: account.id, contactId: null, actorId: note.authorId, channel: "NOTE", direction: null,
      eventType: "NOTE_ADDED", sourceType: "Note", sourceId: note.id, subject: note.isAutoGenerated ? "Automated account note" : "Account note",
      summary: clipped(note.content), occurredAt: note.createdAt, metadata: { sentiment: note.sentiment, historical: true }, createdAt: note.createdAt,
      contact: null, actor: note.author,
    })),
    ...messages.map(message => ({
      id: `sms-${message.id}`, accountId: account.id, contactId: message.contactId, actorId: message.authorId, channel: "SMS", direction: message.direction,
      eventType: "MESSAGE_RECORDED", sourceType: "SmsMessage", sourceId: message.id, subject: null, summary: clipped(message.body), occurredAt: message.createdAt,
      metadata: { fromNumber: message.fromNumber, toNumber: message.toNumber, mediaUrl: message.mediaUrl, historical: true }, createdAt: message.createdAt,
      contact: message.contact, actor: message.author,
    })),
    ...calls.map(call => ({
      id: `call-${call.id}`, accountId: account.id, contactId: call.contactId, actorId: call.authorId, channel: "CALL", direction: call.direction,
      eventType: "CALL_RECORDED", sourceType: "CallLog", sourceId: call.id, subject: call.status, summary: clipped(call.aiSummary || call.notes || call.transcript), occurredAt: call.createdAt,
      metadata: { duration: call.duration, sentiment: call.aiSentiment || call.zohoSentiment, historical: true }, createdAt: call.createdAt,
      contact: call.contact, actor: call.author,
    })),
    ...emails.map(email => {
      const occurredAt = email.sentAt || email.receivedAt || email.createdAt
      return {
        id: `email-${email.id}`, accountId: account.id, contactId: email.contactId, actorId: email.userId, channel: "EMAIL", direction: email.direction,
        eventType: "EMAIL_RECORDED", sourceType: "Email", sourceId: email.id, subject: email.subject, summary: clipped(email.preview || email.body), occurredAt,
        metadata: { fromAddress: email.fromAddress, toAddress: email.toAddress, status: email.status, provider: email.provider, historical: true }, createdAt: email.createdAt,
        contact: null, actor: email.userId ? emailUserMap.get(email.userId) || null : null,
      }
    }),
  ]

  const indexedSources = new Set(indexed.map(event => `${event.sourceType}:${event.sourceId}`.toLowerCase()))
  const events = [...indexed, ...historical.filter(event => !indexedSources.has(`${event.sourceType}:${event.sourceId}`.toLowerCase()))]
    .sort((left, right) => right.occurredAt.getTime() - left.occurredAt.getTime() || right.id.localeCompare(left.id))
    .slice(0, limit)

  return NextResponse.json({
    success: true,
    events,
    nextBefore: events.length === limit ? events.at(-1)?.occurredAt.toISOString() : null,
  })
}
